### ISSUE TITLE
Enhance: Ui of the latest losts section

### ISSUE THREAD

**Issue by Pragati-3003** [GameSphere-MultiPlayer/GameSphere#102]
### Give a brief about the bug ✍️

I would like to change the UI of the latest post section. 
![IMG_20230527_110728](https://github.com/Aman1-coder/GameSphere/assets/132778037/46ff29ef-06b4-4836-a576-3f42dbde190c)
So, please assign this issue to me under GSSOC'23. 

### What is the expected behavior? 🤔

Descriptions would like to change the cards of the late5 post section. 

### Provide step by step information reproduce the bug 📄

I would like to add cool hover effects on the cards. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@Pragati-3003 Could you show me some sample degines.
If you need any help ask to mentor?
Connect - 
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by Durgesh4993** [comment]
Hello @Pragati-3003 ,
If you have some more interactive desgine related, you can DM me on LinkedIn

**Comment by Pragati-3003** [comment]
> Hello @Pragati-3003 , If you have some more interactive desgine related, you can DM me on LinkedIn

sure

**Comment by Pragati-3003** [comment]
> @Pragati-3003 Could you show me some sample degines. If you need any help ask to mentor? Connect - LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/ GitHub : https://github.com/Durgesh4993

![Uploading IMG_20230527_214635.jpg…]()
This is the sample design. 
If you wanna any other design than please inform me.
