### ISSUE TITLE
[New game]: SUDOKU

### ISSUE THREAD

**Issue by AnanyaSDhar** [GameSphere-MultiPlayer/GameSphere#103]
### 🎮 Game Request

Game logic and basic description
1. It will be a Sudoku game, with interesting UI
2. Users can even choose different size of sudoku
sizes

![image](https://github.com/Aman1-coder/GameSphere/assets/90474789/27308409-c714-4f5d-95d3-b1d146a90b3d)

### Point down the features

Game points
1. There will be points based on Timer and No. of correct moves
2. Larger SUDOKU will have the higher scoring opportunity

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@AnanyaSDhar Could you please explain this is single player or multiplayer game , if single player then try to create some  multiplayer games then I'll assign you

**Comment by AnanyaSDhar** [comment]
Well this can also be made in multiplayer mode, where all the users in the group will be provided with the same puzzle and ranking will be given based on score (scoring method is mentioned above).

**Comment by Aman1-coder** [comment]
Ok nice

**Comment by Aman1-coder** [comment]
I'll assign you @AnanyaSDhar 
If you need any help ask to mentor?
Connect -
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by AnanyaSDhar** [comment]
Thank you for assigning the issue. I'll try to complete it as soon as possible.
