### ISSUE TITLE
[New game]: Snake And Ladder

### ISSUE THREAD

**Issue by whiteknight16** [GameSphere-MultiPlayer/GameSphere#105]
### 🎮 Game Request

Make the snake and ladder game using html css and js 

### Point down the features

- Classic Rules
- Support Upto 4 players
- First to 100 Wins

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by whiteknight16** [comment]
Kindly assign me this issue

**Comment by Aman1-coder** [comment]
@whiteknight16 ok I'll assign you the project first create a folder then create game section then create your game

**Comment by Aman1-coder** [comment]
If you need any help ask to mentor?
Connect with mentor:
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by whiteknight16** [comment]
Okay thanks
