### ISSUE TITLE
No option to switch between dark and light mode

### ISSUE THREAD

**Issue by Crusher95574** [GameSphere-MultiPlayer/GameSphere#114]
### Give a brief about the bug ✍️

No option to switch between dark and light mode which makes in difficult for user to use the website under different time period and gives a toll on the eyes 

### What is the expected behavior? 🤔

User able to switch the color theme which makes the website more user friendly and makes site highly attractive 

### Provide step by step information reproduce the bug 📄

I can make add a button in the navbar from which user can switch between dark and light mode effciently 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
I'll assign you @Crusher95574 
If you need any help ask to mentor?
Connect -
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
