### ISSUE TITLE
[New game]:  Hangman Game

### ISSUE THREAD

**Issue by vishalkumarmahto** [GameSphere-MultiPlayer/GameSphere#129]
### 🎮 Game Request

 A hangman game gives the user the choice of three different categories: Fruits, Animals, and Countries. After choosing a category, the computer chooses a word from the category selected. The user has to guess the word using the letter buttons.

### Point down the features

It gives the user the option to make six wrong attempts before he loses the game. If the user guesses the word correctly, we display a winning message. If not, we display a lost message and also a restart button.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by smty2018** [comment]
@Durgesh4993 can you please assign it to me. it has been one month since assigned to the original assignee, still no response.it will complete within 3-4 days.
