### ISSUE TITLE
LUDO GAME

### ISSUE THREAD

**Issue by Killer2OP** [GameSphere-MultiPlayer/GameSphere#15]
###  **Creating the LUDO Game**
I can create the ludo game using HTML , CSS and JS.
Assign me this under GSSoC'23.

**Comment by Srideepthi2384** [comment]
I can work on this using different types like static responsive html and css.. So plz assign me this

**Comment by DhairyaMajmudar** [comment]
please assign this issue to me, I will contribute to this issue under GSSoC'23. I can create a mind-blowing memory game with pretty amazing UI with the help of CSS and JavaScript

**Comment by Aman1-coder** [comment]
@Killer2OP Best of luck for contributions I'll assign you this task, If you need help so contact to mentor
LinkedIn: https://www.linkedin.com/in/durgeshkumar4993/
GitHub: https://github.com/Durgesh4993

**Comment by Killer2OP** [comment]
thank you sir
