### ISSUE TITLE
[New game] [GSSoC'23]: add a tic-tac-toe game

### ISSUE THREAD

**Issue by SoarinSkySagar** [GameSphere-MultiPlayer/GameSphere#161]
### 🎮 Game Request

Game logic and basic description
The game will be a tic-tac-toe game and will be made using HTML, CSS and JavaScript.

### Point down the features

Game points
Just like a regular tic tac toe game, this will make the person who can score 3 of his mark's (X or O) in a single line the winner.
The game will be turnwise, with each player taking turns alternatively.

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by SoarinSkySagar** [comment]
Please assign this to me, @Aman1-coder , @Durgesh4993

**Comment by AyushPathak7074** [comment]
for seamless view of website and as per users comfort .will try to will build a tic tac toe game.
assign this issue to me.
i'm GSSOC'23 contributor
