### ISSUE TITLE
[New game]: Minesweeper

### ISSUE THREAD

**Issue by singh-anushka** [GameSphere-MultiPlayer/GameSphere#171]
### 🎮 Game Request

Game logic and basic description
In Minesweeper, you need to uncover all the squares on the grid without detonating any mines. The grid is initially covered with hidden squares, some of which contain mines. Your task is to reveal the safe squares while avoiding the explosive mines lurking beneath.
This is prepared using HTML, CSS and JavaScript.

The game is played on a rectangular grid, typically ranging from 8x8, with 5 mines. Each square on the grid can be in one of three states: hidden, revealed, or flagged. Initially, all squares are hidden, and you must choose which squares to reveal.

To uncover a square, you can click on it using your mouse or touch the corresponding area on a touchscreen device. Once a square is revealed, it will display a number, indicating how many mines are adjacent to that square. Use these numbers strategically to deduce the location of mines and proceed further.

### Point down the features

Game points
There are no points earned in intermediate moves, but if you encounter a mine, it's game over! The mine will explode, revealing its location, and you'll have to start again. However, if you successfully uncover all the safe squares without triggering any mines, You Win!

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
Hello @singh-anushka i think so you have any missunderstanding, @Avdhesh-Varshney is currently not in out team if you need any help you are able to ask with mentor and project admin

connect with me:
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
Github : https://github.com/Durgesh4993

**Comment by Durgesh4993** [comment]
@Avdhesh-Varshney if you want to work with us we are welocme you

**Comment by Durgesh4993** [comment]
And one more thing @singh-anushka first complete this task then i'll assign you more tasks

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney if you want to work with us we are welocme you

It's my pleasure @Durgesh4993 
I will give my best

**Comment by singh-anushka** [comment]
> Hello @singh-anushka i think so you have any missunderstanding, @Avdhesh-Varshney is currently not in out team if you need any help you are able to ask with mentor and project admin
> 
> connect with me: LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/ Github : https://github.com/Durgesh4993

Sorry it was a mistake I thought he is in the team

**Comment by singh-anushka** [comment]
> And one more thing @singh-anushka first complete this task then i'll assign you more tasks

I made the PR, now please assign me 

[Connect 4](https://github.com/GameSphere-MultiPlayer/GameSphere/issues/165)
[Doodle Jump](https://github.com/GameSphere-MultiPlayer/GameSphere/issues/166)
[Chrome Dinosaur Game](https://github.com/GameSphere-MultiPlayer/GameSphere/issues/167)
[Space Invaders](https://github.com/GameSphere-MultiPlayer/GameSphere/issues/168)
[Atari Breakout](https://github.com/GameSphere-MultiPlayer/GameSphere/issues/169)
[Guess the colour RGB](https://github.com/GameSphere-MultiPlayer/GameSphere/issues/170)
[Wordle](https://github.com/GameSphere-MultiPlayer/GameSphere/issues/172)
[Tower Blocks](https://github.com/GameSphere-MultiPlayer/GameSphere/issues/173)
