### ISSUE TITLE
[New game]: Snake game

### ISSUE THREAD

**Issue by bhavyasingh75** [GameSphere-MultiPlayer/GameSphere#174]
### 🎮 Game Request

Game logic and basic description: The original snake game that moves and grows whenever it eats food. If it bites his own tail or crashes, the game ends.

### Point down the features

Game points: The points would increase as the length of the snake increases on eating the food.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
Sirs @mahamat-abdelkerim-abakar @Durgesh4993 please /assign this snake feeder game to me.
