### ISSUE TITLE
[New game]: Pacman

### ISSUE THREAD

**Issue by bhavyasingh75** [GameSphere-MultiPlayer/GameSphere#175]
### 🎮 Game Request

Game logic and basic description: Classic Pacman running from monsters and eating the trail of food.  If Pacman meets the monster, the monster gobbles up Pacman and the game ends.

### Point down the features

Game points: The points increase on the basis of eating the food trails till it is finished, also avoiding the interaction with the monsters. 
Can you assign this issue to me?

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@mahamat-abdelkerim-abakar /assign this task to me.

**Comment by Avdhesh-Varshney** [comment]
Sirs @mahamat-abdelkerim-abakar @Durgesh4993 please /assign this task to me

**Comment by Avdhesh-Varshney** [comment]
@mahamat-abdelkerim-abakar sir please open this issue so that i will request for closing at the time of creation of pull request.
