### ISSUE TITLE
Adding tic tac toe

### ISSUE THREAD

**Issue by anan262** [GameSphere-MultiPlayer/GameSphere#18]
I'm confident I can do this s both single and multiplayer as I have experience in game creation..I am super excited and thrilled to be contributing for GSSOC and hoping that I would get to contribute to this one!

**Comment by DhairyaMajmudar** [comment]
please assign this issue to me, I will contribute to this issue under GSSoC'23. I can create a mind-blowing memory game with pretty amazing UI with the help of CSS and JavaScript

**Comment by arunavabasu-03** [comment]
I would like to work on this

**Comment by Sreenija03** [comment]
Can you please assign this issue to me under GSSOC 2023

**Comment by Aman1-coder** [comment]
@anan262 ok as we know that tac toe is a simple so  just try to make a attractive interface of game .'ll assign you the project first create a folder for game section then create your folder then create your game. i`ll hope you understand what i am trying to say

**Comment by anan262** [comment]
Yeahh sure,thanks!
