### ISSUE TITLE
[New game]: Dice Roll Game

### ISSUE THREAD

**Issue by Teddy1404** [GameSphere-MultiPlayer/GameSphere#181]
### 🎮 Game Request

Game logic and basic description
This game has a simple user interface with a heading, a paragraph explaining the game, a "Roll Dice" button, and a div to display the dice result. When the user clicks the "Roll Dice" button, the rollDice function is called. Inside this function, a random number between 1 and 6 is generated using Math.random() and Math.floor(). The dice result is then displayed in the diceResult div.

### Point down the features

Game points
Single player can play for two players .

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@mahamat-abdelkerim-abakar sir, /assign this task to me.

**Comment by Avdhesh-Varshney** [comment]
Sirs @mahamat-abdelkerim-abakar @Durgesh4993 please /assign this task to me as i have completed this game.
