### ISSUE TITLE
[New game]: Brick Breaker Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [GameSphere-MultiPlayer/GameSphere#187]
### 🎮 Game Request

Game logic and basic description

The game logic is to clear all the bricks on the screen by hitting them with the ball, while avoiding letting the ball fall off the paddle. 
Power-ups and different brick formations add variety and challenge to the gameplay. 
The game ends when all the bricks are destroyed or the player runs out of lives.

### Point down the features

Game points

1. Brick Destruction
2. Level Completion
3. Time Bonus, etc.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
Sir, @mahamat-abdelkerim-abakar @Durgesh4993 /assign this task to me to contribute under GSSoC'23

**Comment by Avdhesh-Varshney** [comment]
Sirs @mahamat-abdelkerim-abakar @Durgesh4993 please /assign this task to me.

**Comment by Durgesh4993** [comment]
@Avdhesh-Varshney This game is already exist in website please raise another issue or try to create mutlplayer game

**Comment by Avdhesh-Varshney** [comment]
@Durgesh4993 I have created 2 multi player games #242 #243 as you have suggested to me.
Please assign them to me to contribute under GSSoC'23.
Thank you so much !
