### ISSUE TITLE
[New game]: Rabbit Rush

### ISSUE THREAD

**Issue by aditya-agr** [GameSphere-MultiPlayer/GameSphere#188]
### 🎮 Game Request

A retro styled game testing your reflexes and precision on the keyboard or mouse. Your main aim is to save the rabbit from the wolf running behind him to catch him. You can do it by jumping the rabbit over the hedgehogs that come in his path and by grabbing the carrots that increase its speed.

### Point down the features

-Easy to play
-Melodious background music
-Scoring system so that you can compare points with your friends.
-Responsive design for most of the monitors.

**Screenshot of Game-**

![rabbit](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/101137544/34609992-1e15-4ee0-a543-0c3d97839d4d)

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by aditya-agr** [comment]
I am a GSSoC23 contributor please assign me this issue.
@Avdhesh-Varshney  @Durgesh4993 please assign me this issue.

**Comment by Durgesh4993** [comment]
@aditya-agr This game is already added
