### ISSUE TITLE
[New game]: FLIP THE CARD 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [GameSphere-MultiPlayer/GameSphere#190]
### 🎮 Game Request

Game logic and basic description
- Flip is a timed card memory game. When starting a level, there's a red bar on top of the screen that shows how much time you have left.
- Click the green cards to see what symbol they uncover and try to find the matching symbol underneath the other cards.
- Uncover two matching symbols in a row to eliminate them from the game.
- Eliminate all cards as fast as you can to win the game. Have fun FLIPing!

### Point down the features

Game points
- The game will save your stats locally, via localStorage.
- Click the F to see your stats.
- Click I for these intructions.
- If lost cards appear as LOST,and initially cards appear as FLIP.

### Select The Game Type

Single Player

### Screenshot
![](https://user-images.githubusercontent.com/100008872/242876568-1a1b6214-2bb8-4e4c-bf30-acfaec393d5a.png)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@0xabdulkhalid Please try to creat a responsive game
