### ISSUE TITLE
[New game]: add chess game

### ISSUE THREAD

**Issue by S-ishita** [GameSphere-MultiPlayer/GameSphere#196]
### 🎮 Game Request

The game is a two-player chess game played on an 8x8 chessboard. Each player has a set of chess pieces and takes turns making moves. Players can select a piece by clicking on it and then choose a valid destination square for that piece. The game enforces the rules of chess, ensuring that moves are legal and capturing opponent's pieces when necessary. The game also handles special moves like castling, en passant, and promotion. It checks for check and checkmate conditions to determine if a player's king is in danger or if the game is over. The game interface is updated to display the current board state, player turn, captured pieces, and other relevant information.

### Point down the features

- Flipping the Board: Allow players to flip the chessboard, changing the perspective and orientation of the game. This feature can be useful for players who prefer different viewing angles or want to test their skills from both sides of the board.
- I will try to implement some cool features such as En Passant, Castling, Threefold Repetition etc.

### Select The Game Type

Multiplayer, Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@S-ishita in single player folder
