### ISSUE TITLE
[New game]: PACIFIC AIR BATTLE

### ISSUE THREAD

**Issue by 0xabdulkhalid** [GameSphere-MultiPlayer/GameSphere#197]
### 🎮 Game Request

Game logic and basic description
- In this game, you will take control of a fighter jet and engage in aerial combat against enemy jets.
- You will need to use your skills and experience to dodge enemy fire and take down your targets.
- This game has good graphics 

### Point down the features

Game points
- The objective of the game is to destroy all of the enemy jets. You can do this by using your weapons to shoot them down or by ramming them.
- This game is challenging and will require you to use all of your skills and experience to succeed.
- You will get points for Attacking the enemies, you can get mediboxes to boost your health and much more!

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@0xabdulkhalid  Try to creat a responsive game
