### ISSUE TITLE
[New game]: PING PONG - ( MULTIPLAYER )

### ISSUE THREAD

**Issue by 0xabdulkhalid** [GameSphere-MultiPlayer/GameSphere#198]
### 🎮 Game Request

Game logic and basic description
- Ping pong, also known as table tennis, is a sport in which two or four players hit a lightweight ball back and forth across a table using small solid rackets. 
- They must prevent the ball from touching the surface of the table on their side

### Point down the features

Game points
- Players must allow a ball played towards them to bounce once on their side of the table and must return it so that it bounces on the opposite side. 
- A point is scored when a player fails to return the ball within the rules. A player or team wins a game by scoring 11 points with a two-point margin. 
- A match is usually the best of any odd number of games (usually the best of five).

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@0xabdulkhalid  First complete those two assign tasks
