### ISSUE TITLE
[Enhancement]: On hover card demo effect. On Home page in TOP POPULAR GAMES section.

### ISSUE THREAD

**Issue by sunny0625** [GameSphere-MultiPlayer/GameSphere#206]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/76521579/0e37240f-5c88-41d8-b24c-2f937b827bba)

### Describe the solution you'd like

Solution steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@sunny0625 when click on card can we able to show the demo vedio for game

**Comment by sunny0625** [comment]
That's a great idea!

**Comment by Durgesh4993** [comment]
Ok i'll assign, you can start work

**Comment by Durgesh4993** [comment]
if you need any help you can message me

**Comment by sunny0625** [comment]
@Durgesh4993 Yeah, My vivas are going in between, So that's why busy. And want to ask about getting a problem with getting demo videos for all games.

**Comment by Durgesh4993** [comment]
@sunny0625 Don't worry complete your personal work, I'll assign this work to anyone else
