### ISSUE TITLE
Paint game[New game]: 

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#213]
### 🎮 Game Request

Want to add paint game 

### Point down the features

teach stack going to use is python

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@shraddha761 can you explain more about game

**Comment by shraddha761** [comment]
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/106100728/9fe79344-3043-4809-816b-4d910a6fbe40)

Sorry for delay this is the UI of game in which based on color it select that color

**Comment by Durgesh4993** [comment]
@shraddha761 But i don't thing so it is game, could you please explain how a user play this game
