### ISSUE TITLE
[Question]:  Can I Recreate logo of  GameSphere?

### ISSUE THREAD

**Issue by Dimple-Choudhary** [GameSphere-MultiPlayer/GameSphere#217]
### Description
I have created an issue in the "Question or support request" because I am not sure whether we can add other features to the website GameSphere,if we can I would Like to recreate the logo of  GameSphere :)
@Durgesh4993 , If you would like to have a new logo for the game-sphere! assign me this issue under GSSoC'23.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
you can contact me

**Comment by Dimple-Choudhary** [comment]
sure ,On discord?

**Comment by Durgesh4993** [comment]
ok

**Comment by Dimple-Choudhary** [comment]
hey, @Durgesh4993 Below are a few logo designs 
![Gamesphere-logo](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/96401557/12a6cbd2-97ab-4d9d-a34d-a84c861fa7c3)
If would like any changes let me know :)
Also, I want to ask you a few questions about recreating a logo. In case you didn't liked the above design  
Linkedin:-https://www.linkedin.com/in/dimple-choudhary--/

**Comment by Durgesh4993** [comment]
@Dimple-Choudhary  I want to talk with you please accept my request on linkedin
