### ISSUE TITLE
[Question]: Can I add bouncing ball animation on home page ?

### ISSUE THREAD

**Issue by Dimple-Choudhary** [GameSphere-MultiPlayer/GameSphere#225]
### Description
 Can I add bouncing ball animation on home page ?
Demo:-
![home page](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/96401557/f9551ac2-95c4-48f1-bbd5-25e08e704efa)

This is just an image of the ball it will be animated.
@Durgesh4993 , will you assign me this issue under GSSoC'23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
one more thing please check the responiveness when you work on this

**Comment by Durgesh4993** [comment]
if you need any help you can contect me

**Comment by Dimple-Choudhary** [comment]
Yes , I will pay attention to responsiveness .
