### ISSUE TITLE
[Bug]: Adding hover effect  on New Game Button 

### ISSUE THREAD

**Issue by akankshachanana1** [GameSphere-MultiPlayer/GameSphere#229]
### Give a brief about the bug ✍️

Description
Currently there is no hover effect on The "New Game" button and the bottom to top button . I want to work on this issue by adding hover effect (in accordance with UI of the site)

### What is the expected behavior? 🤔

Description There should be hover effect on the buttons in order to make the site more interacting 

### Provide step by step information reproduce the bug 📄

Description
I will add the Hover effect in accordance with UI of site and the hover effect added on rest of buttons

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
This task is already assigned
