### ISSUE TITLE
[New game]:  Candy Crush Game

### ISSUE THREAD

**Issue by PoulavBhowmick03** [GameSphere-MultiPlayer/GameSphere#231]
### 🎮 Game Request

The goal is to match at least three candies of the same colour and type in a row or column to clear them from the board. With each successful match, players earn points.
This project is built on a basic web tech stacks such as HTML, CSS and Javascript.

### Point down the features

Scoring system to for comparison.
Responsive design.
Random candy generation.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by PoulavBhowmick03** [comment]
@Aman1-coder @Durgesh4993 can this be assigned?

**Comment by Durgesh4993** [comment]
@PoulavBhowmick03 this game is already exist
