### ISSUE TITLE
[New game]: Tic-tac-toe

### ISSUE THREAD

**Issue by pavitrachavda97** [GameSphere-MultiPlayer/GameSphere#234]
### 🎮 Game Request

Game logic and basic description
This game will be created using HTML, CSS and JavaScript. This is two player game. User will play this game turn by turn. And will check for win after every move, if anyone won then game is over and they can start play again.

### Point down the features

Game points
First game board will be Initialize.
Starting player will be X
Player will select board
Check for win
Update board
Switch player
If player win then game stopped

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@pavitrachavda97 This game is already exist
