### ISSUE TITLE
Add a word guessing game

### ISSUE THREAD

**Issue by DhairyaMajmudar** [GameSphere-MultiPlayer/GameSphere#25]
To create a word guessing game to enhance memory retention using HTML, CSS and JS

**Comment by DhairyaMajmudar** [comment]
please assign this issue to me

**Comment by Aman1-coder** [comment]
@DhairyaMajmudar we are currently working on home page section so please wait some time then I'll assign you

**Comment by DhairyaMajmudar** [comment]
Ok Sir 👍
