### ISSUE TITLE
[Bug]: No Contact Us Page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [GameSphere-MultiPlayer/GameSphere#250]
### Give a brief about the bug ✍️

Currently  cicking on Contact us leads to this blank page

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/133862694/9b0fe482-ba32-48b8-8734-268102fa26d4)

### What is the expected behavior? 🤔

It should open a separate contact us page after clicking on it

### Provide step by step information reproduce the bug 📄

I would create a separate Contact Us page adhering to the website theme and link it to the navbar

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Saksham0205** [comment]
Can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by PoulavBhowmick03** [comment]
@Durgesh4993 Please assign this

**Comment by sumitkr2000** [comment]
Can i work on this issue?
