### ISSUE TITLE
[New game]: Candy crush game

### ISSUE THREAD

**Issue by Abhinavcode13** [GameSphere-MultiPlayer/GameSphere#258]
### 🎮 Game Request

Candy Crush is a popular match-3 puzzle game where players swap colorful candies to create matching sets.

The game board consists of a grid filled with different colored candies. Each candy occupies a single cell on the grid.

Creating matches of four or more candies can generate special candies with unique abilities. For example, matching four candies in a row creates a "Striped Candy" that clears an entire row or column when activated. Matching five candies in an "L" or "T" shape creates a "Wrapped Candy" that explodes and clears surrounding candies when activated.

### Point down the features

Game points:

score Increases by +1 by every matching 3 candies

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
This game is already exist @Abhinavcode13
