### ISSUE TITLE
[New game]: Code breakout game

### ISSUE THREAD

**Issue by Abhinavcode13** [GameSphere-MultiPlayer/GameSphere#260]
### 🎮 Game Request

Breakout is a classic arcade-style game where the player controls a paddle to hit a ball and break bricks.
The objective of the game is to break all the bricks on the screen using the ball and paddle.
The player controls the paddle using the left and right arrow keys to prevent the ball from falling off the bottom of the screen.
The ball bounces off the walls, paddle, and bricks, changing its direction accordingly.
There are multiple rows and columns of bricks arranged on the screen, and the player needs to hit the ball against the bricks to break them.
Each time the ball collides with a brick, the brick disappears, and the player earns points.
The game ends when all the bricks are destroyed or if the ball falls off the bottom of the screen.
The player's score is displayed on the screen, increasing with each brick broken.
The game features colorful graphics and sound effects to enhance the gaming experience.
The layout of the bricks can vary, creating different levels and challenges for the player.
The game can have additional features such as power-ups, special bricks, and different ball or paddle behaviors to add variety and complexity.

### Point down the features

breaking each brick gives 100 points

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Abhinavcode13** [comment]
Please assign me this issue @Durgesh4993

**Comment by Durgesh4993** [comment]
This game is already exist @Abhinavcode13
