### ISSUE TITLE
[New game]: [GSSOC '23] : Drum Playing Game

### ISSUE THREAD

**Issue by sujanrupu** [GameSphere-MultiPlayer/GameSphere#273]
## Game logic and basic description:
Drum playing game is a game developed using HTML, CSS, JavaScript. There are some specific buttons indicating different symbols of drum images.  If plyer clicks on a specific image, the specific sound will ring.

## Game points:

- On screen there will be different symbols of drum, each of which signifies different music tones
- If user clicks on a specific tone, then that tone will be played.
- If wrong button is pressed then wrong music will be played.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@sujanrupu Could you please send a demo vedio

**Comment by sujanrupu** [comment]
[244922867-e1afbc65-2e27-4695-882e-7b856ed67782.webm](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/103595490/9d7d78cd-bf81-4d06-b9e3-9397771bc2e6)


@Durgesh4993 please check
