### ISSUE TITLE
[New game]: ROCK PAPER SCISSORS GAME

### ISSUE THREAD

**Issue by MohammadAsiya** [GameSphere-MultiPlayer/GameSphere#281]
### 🎮 Game Request

Game logic and basic description:
The game of Rock Paper Scissors is a simple hand game played between two people. The players count to three in unison and simultaneously throw one of three hand signs representing rock, paper, or scissors. The winner is determined by the rules below:

Rock beats scissors: Rock smashes scissors.
Paper beats rock: Paper covers rock.
Scissors beats paper: Scissors cut paper.
If both players choose the same hand sign, it's a tie and the game is usually replayed.

### Point down the features

Game points:
Rock beats scissors: Rock win.
Paper beats rock: Paper win.
Scissors beats paper: Scissors win.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@MohammadAsiya This game is altready exist try to raise another issue
