### ISSUE TITLE
[Bug]: On clicking contact page blank screen is coming so i want to add contact us page there

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#287]
### Give a brief about the bug ✍️

In nav bar on click contact link white page is coming their is no contact us page so i want to add contatc us page 

### What is the expected behavior? 🤔

On clicking contact in navabar ,a contact page must appear

### Provide step by step information reproduce the bug 📄

1. Firstly I will make a design of contact page which is most suitable with the website overall design.
2. Then I will create a contact page using html ,css and javascript according to that design .
3. Then I will add suitable links to it 

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by raju-kumar21** [comment]
design? @lakhan06

**Comment by lakhan06** [comment]
> design? @lakhan06

I didn't make it yet @raju-kumar21

**Comment by lakhan06** [comment]
I currentlyy don't have a proper design but had a previously made contact page whose theme is  similer to gamespher and a after changes it can be look good.
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/a842b7af-415e-47f5-be38-f319a4e1a358)
I can add map to this page and also can add some images related to gaming and some animation so that it can properly align with the Gamesphere theme and can also add more input field if needed .
If you have any suggestion or regarding it then it will be very helpful .
I request your attention and consideration in reviewing ans assigning me this issue @raju-kumar21 sir.
Thankyou



.

**Comment by Durgesh4993** [comment]
@lakhan06 please check out there are some issue in changing the theam can you solve

**Comment by lakhan06** [comment]
> @lakhan06 please check out there are some issues are occured in website in theam can you solve

ok give me time i solve it .

**Comment by lakhan06** [comment]
> @lakhan06 please check out there are some issues are occured in website in theam can you solve

there is issues in links that why it happen i will fix that @Durgesh4993

**Comment by Durgesh4993** [comment]
@lakhan06 ok try to resolve it

**Comment by lakhan06** [comment]
> @lakhan06 ok try to resolve it



> @lakhan06 ok try to resolve it

@Durgesh4993  i resolved the issue and give a pull request merge it and then it will solved

**Comment by lakhan06** [comment]
@Durgesh4993 What email ,number ,location should i add in contact page

**Comment by Durgesh4993** [comment]
No that good no need to add details

**Comment by lakhan06** [comment]
> No that good no need to add details

ok then i will pull request
