### ISSUE TITLE
[New game]: Typing game

### ISSUE THREAD

**Issue by Abhinavcode13** [GameSphere-MultiPlayer/GameSphere#311]
### 🎮 Game Request

Game logic and basic description

Usually, a typing game will require the player to quickly or precisely type in words - or individual letters, numbers, or other keys - that display on the screen to proceed in the game, functioning as both a challenge and a means to improve one's skill at touch typing.

### Point down the features

Game points

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Abhinavcode13** [comment]
@Durgesh4993 assign me this

**Comment by mahamat-abdelkerim-abakar** [comment]
@Abhinavcode13 could you please explain more about game or send a demo video
