### ISSUE TITLE
[New game]: Mastermind game

### ISSUE THREAD

**Issue by Abhinavcode13** [GameSphere-MultiPlayer/GameSphere#312]
### 🎮 Game Request

Game logic and basic description:

The code is a four color code containing the colored buttons displayed. The code may contain multiples of the same color. Try to guess the correct code (color and order) by clicking on the colored buttons and then hitting the submit button. Your guess will then be compared to the code. For every correct color that is in the correct position, a black peg will be displayed. However, for every correct color that is in the wrong position, a white peg will be displayed. Use this feedback to determine the correct code

Crack the hidden code 

### Point down the features

Game points

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Abhinavcode13** [comment]
@Durgesh4993 assign me

**Comment by mahamat-abdelkerim-abakar** [comment]
could you please explain more about game or send a demo video or some screenshoot
