### ISSUE TITLE
[New game]: Pong Game

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#316]
### 🎮 Game Request

It is a multiplayers game in which two players play together and there is a ball which move between two walls and players have to hit the ball before it touches there respective wall.

### Point down the features

- It is a multiplayer game .
- There will be a ball which move between two walls .
- Players need to try that ball did not hit their wall using a moving vertical stick.
- If ball touches a player wall then its opponent point increase with one.
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/6ed569b4-aef5-4fe3-b0b2-d0b3ae8b906a)

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

@Durgesh4993  please assign me this issue

**Comment by lakhan06** [comment]
@Durgesh4993 please assign this issue to me

**Comment by Durgesh4993** [comment]
@lakhan06 this game is also exist
