### ISSUE TITLE
[New game]:  Hangman Game

### ISSUE THREAD

**Issue by chinmayjain08** [GameSphere-MultiPlayer/GameSphere#320]
### 🎮 Game Request

Game logic and basic description:
The game starts with a hidden word.
The player takes turns guessing letters.
If the player guesses a letter that is in the word, the letter is revealed.
If the player guesses a letter that is not in the word, a body part is added to the hangman drawing.
The game ends when the player either guesses all the letters in the word or when the hangman is complete.

### Point down the features

Game points:
Multiple difficulty levels
The ability to choose from a variety of word lists
The ability to play against another player
The ability to save and resume games
The ability to customize the hangman drawing

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@chinmayjain08 this game already exist
