### ISSUE TITLE
[Bug]: Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [GameSphere-MultiPlayer/GameSphere#326]
### Give a brief about the bug ✍️

The website does not have meta tags with descriptions. This means that the website is not as visible in search results, and users are less likely to click on the website's links.

### What is the expected behavior? 🤔

The website should contain important meta tags. This will help the website rank higher in search results and attract more visitors.

### Provide step by step information reproduce the bug 📄

Add various meta tags to enhance the SEO of the website.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by mahamat-abdelkerim-abakar** [comment]
Well
