### ISSUE TITLE
[Enhancement]: I want to add About us page in the website 

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#330]
### Is your enhancement request related to a problem? Please describe.➕

Their is no about us page in the website so I  want to add it .

### Describe the solution you'd like

- Firstly I will choose the deign which is most suitable for the website and which matches with the theme of website.
- Then i will find image which will I add in the website.
- Then i code the about us page according to design using Html,css and javascript.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

@Durgesh4993 Sir PLease assign me this issue

**Comment by Durgesh4993** [comment]
@lakhan06 Currently we don't decided about page

**Comment by Durgesh4993** [comment]
So please try to raise any other issue

**Comment by lakhan06** [comment]
> So please try to raise any other issue
OK then please i assign issue #316
