### ISSUE TITLE
[New game] [Insect Catch Game]: 

### ISSUE THREAD

**Issue by JadavShraddha** [GameSphere-MultiPlayer/GameSphere#333]
### 🎮 Game Request

<h2>Game logic and basic description:<h2>

This game is created with the help of html, css and javascript.
In this game first you can choose your favorite insect.The objective of the game is to catch as many insects as possible within a given time limit.
The insects come in various shapesand they move quickly and unpredictably across the screen.
The catchers must be quick and agile to track the insects' movements and snatch them out of the air.

### Point down the features

###Game points
change the insect type
show user points and time on screen
sound feature
Select The Game Type
Single Player

Pictures
![1st](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/95160083/9e1e2c68-cd0e-4a02-baaf-530be69b0cf2)
![2nd](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/95160083/e3eeda84-cff5-45c4-9c0d-45743f16a386)

###Select program in which you are contributing
GSSoC23

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@JadavShraddha Could you please create some other issue
