### ISSUE TITLE
[New game] [Snake Game Using Python]: 

### ISSUE THREAD

**Issue by JadavShraddha** [GameSphere-MultiPlayer/GameSphere#335]
### 🎮 Game Request

Game logic and basic description

The Snake game in Python has a clear objective of catching the maximum number of blocks without hitting the cross border or the wall as they say.
 With the help of the Pygame library, I shall be learning building the Snake game in Python from scratch.

### Point down the features

Game points

The player controls a long, thin creature, resembling a snake, which roams around on a bordered plane, picking up block, trying to avoid hitting its own tail or the edges of the playing area. Each time the snake eats a block, its tail grows longer, making the game in
creasingly difficult.

![img1](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/95160083/2fa758ae-78f9-4dd2-ba32-d59f09f9b8a5)

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@JadavShraddha One more request please try to create with some unique not a simple
