### ISSUE TITLE
[Bug]: All the links in the Navbar redirects to a new tab.

### ISSUE THREAD

**Issue by trishanu-init** [GameSphere-MultiPlayer/GameSphere#336]
### Give a brief about the bug ✍️

All the internal and external links in the Navbar namely Home,Game,Multiplayer,Join Community and Contact open as a new tab in the browser and some links do not redirect to the home page.

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/85580785/278e82c7-9f56-40f0-9997-1c86d947d917

### What is the expected behavior? 🤔

All the links should not open a new tab every time but redirect to a section within the page or open in he same tab.

I have solved the issue on my local machine and will create a PR once this issue is assigned to me

### Provide step by step information reproduce the bug 📄

Change the Navbar Section of all the html files.

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/85580785/e4fc9ae0-3035-4c51-b86b-1573786f4575

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by mahamat-abdelkerim-abakar** [comment]
Looks good 👍🏻
Well done 🙂
