### ISSUE TITLE
[New game]: Whack a Mole Game

### ISSUE THREAD

**Issue by Vyshnavi21504** [GameSphere-MultiPlayer/GameSphere#339]
### 🎮 Game Request

Whack-a-Mole  involves quick reflexes and hand-eye coordination. The game typically consists of a large console with a series of holes or openings, each housing a plastic mole or target. The objective of the game is to strike or "whack" the moles as they randomly pop up from their holes using a mallet or hammer.

### Point down the features

Earn points for successfully hitting moles and lose points for missing or hitting empty holes.

Suitable for players of all ages.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Vyshnavi21504 sorry this task is already assignd to any other person
