### ISSUE TITLE
[Enhancement]: MUltiplayer Page is blank so i want to add contant in multiplayer game page

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#341]
### Is your enhancement request related to a problem? Please describe.➕

Their is no content in multiplayer page 

### Describe the solution you'd like

I will add content in multiplayer page and add relevant game in it with a proper design which is similar to gamesphere theme

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by lakhan06** [comment]
> ### Is your enhancement request related to a problem? Please describe.➕
> Their is no content in multiplayer page
> 
> ### Describe the solution you'd like
> I will add content in multiplayer page and add relevant game in it with a proper design which is similar to gamesphere theme
> 
> ### Select The Game Type
> Multiplayer
> 
> ### Code of Conduct
> * [x]  I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

@Durgesh4993  SIr please assign me this issue

**Comment by Durgesh4993** [comment]
@lakhan06 Are you able to create some multiplayer game

**Comment by Durgesh4993** [comment]
Hello @lakhan06 i have one task for you, Can you create, when the card is hover then some gameplay will be play automatically, be like youtube

**Comment by lakhan06** [comment]
> Hello @lakhan06 i have one task for you, Can you create, when the card is hover then some gameplay will be play automatically, be like youtube

did you want video of game to be played on hover?

**Comment by Durgesh4993** [comment]
Yes

**Comment by Durgesh4993** [comment]
one more thing don't save vedio in folder you can uplod that vedio, then add their link

**Comment by lakhan06** [comment]
> one more thing don't save vedio in folder you can uplod that vedio, then add their link

ok

**Comment by Durgesh4993** [comment]
If you need any help you can message me

**Comment by Durgesh4993** [comment]
ok

**Comment by lakhan06** [comment]
> @lakhan06 Are you able to create some multiplayer game

i can add all games which are added by other contributors in multiplayer folder if you want because it is blank which not look good

**Comment by lakhan06** [comment]
> If you need any help you can message me

did you have video of games or should i record myself

**Comment by Durgesh4993** [comment]
You should record

**Comment by lakhan06** [comment]
> one more thing don't save vedio in folder you can uplod that vedio, th

> You should record

ok
