### ISSUE TITLE
[New game] [HoverBoard Effect]: 

### ISSUE THREAD

**Issue by JadavShraddha** [GameSphere-MultiPlayer/GameSphere#344]
### 🎮 Game Request

<h2>Game logic and basic description:</h2>

<li>This game is created with the help of html, css and javascript.</li>
<li>In this project, we create a big square board with lots of tiny square boxes on it. We have colored those small square boxes If the mouse cursor goes over the big square box the small tiny square box is colored. It has a simple background big box in the middle. The user has to hover the mouse over the box and it will display a random color. It has a very cool user interface. the project make the website more attractive.</li>

### Point down the features

<h2>Game Pint</h2>
<ol>
<li>colored those small square boxes If the mouse cursor goes over the big square box the small tiny square box is colored</li>
<li>The user has to hover the mouse over the box and it will display a random color</li>
</ol>

<h2>pictures</h2>
![img3](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/95160083/3b951cb6-5de9-4a63-9d4b-bb5e0570d87b)

<h2>Demo video</h2>
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/95160083/e3d480c3-e951-466f-9d29-36251be1911b

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by JadavShraddha** [comment]
please assign me this issue

**Comment by Durgesh4993** [comment]
You have seen my msg in linkedIn
