### ISSUE TITLE
[Enhancement]: On hover game video play 

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#345]
### Is your enhancement request related to a problem? Please describe.➕

no hover effect in images of games

### Describe the solution you'd like

I want to add hover effect in game images so that their video will play on hover so that user get a demo off games 

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by lakhan06** [comment]
@Durgesh4993  i added hover effect in home page .

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/d57b00cb-9f55-47f6-aa9c-08dbac02d970

Is it good? it will take time for me to add it to game page so should i do a pull request for home page or should i complete first the game page and then give a pull request

**Comment by lakhan06** [comment]
@Durgesh4993  their is also a problem if I use links of videos then it sometime take time for videos to load so it will be good if we add these video in a folder then add them.

**Comment by Durgesh4993** [comment]
Ok no issue, But for only home page l am provide only level1 it is ok

**Comment by lakhan06** [comment]
> 



> Ok no issue, But for only home page l am provide only level1 it is ok

ok i will first complete all then give pull request

**Comment by lakhan06** [comment]
> > 
> 
> > Ok no issue, But for only home page l am provide only level1 it is ok
> 
> ok i will first complete all then give pull request and one more question should i add controls in the video or not

**Comment by lakhan06** [comment]
> > > 
> > 
> > 
> > > Ok no issue, But for only home page l am provide only level1 it is ok
> > 
> > 
> > ok i will first complete all then give pull request and one more question should i add controls in the video or not



> Ok no issue, But for only home page l am provide only level1 it is ok

ok i will first complete all then give pull request and one more question should i add controls in the video or not @Durgesh4993

**Comment by Durgesh4993** [comment]
No need to add control

**Comment by lakhan06** [comment]
> No need to add control

ok

**Comment by lakhan06** [comment]
> so don't waste your time you can first complete home page

i completed home page and now working on game page

**Comment by Durgesh4993** [comment]
Because there are many game which is not listed in game page

**Comment by lakhan06** [comment]
> Because there are many game which is not listed in game page

i completed game page and their are problem in links of the game so corrected it and now all are working so no problem their 
and i giving pull request for intire website
