### ISSUE TITLE
Color blast[New game]: 

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#347]
### 🎮 Game Request

in this game plyer has to hit the color cube using space bar 

### Point down the features

if player hit all the cube then he win or if any of cube touches ground then loose

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@shraddha761 First complete old task then i'll assign you more work currently i am closeing the remaining issues
