### ISSUE TITLE
[New game]: Sword Smasher

### ISSUE THREAD

**Issue by PoulavBhowmick03** [GameSphere-MultiPlayer/GameSphere#357]
### 🎮 Game Request

Cubes would be flying up on screen and user has to destroy it before it goes down, or game is over using advanced CSS and Javascript

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/133862694/723655b9-8c72-4348-b388-083cb2f61357

### Point down the features

Game points
1. Intense movement
2. Amazing animations
3. Fast paced and entertaining

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by PoulavBhowmick03** [comment]
@Durgesh4993 Check out

**Comment by Durgesh4993** [comment]
@PoulavBhowmick03 Sorry, don't add this game because last time someone raise a ticket for this game

**Comment by Durgesh4993** [comment]
so please try to create new issue
