### ISSUE TITLE
[Enhancement]: Remove unwanted space from CONTACT US page & Improvement of UI

### ISSUE THREAD

**Issue by vidhimakani74** [GameSphere-MultiPlayer/GameSphere#360]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement:
In the contact us page there are many unwanted space that's why page looks not good. i want to remove it  & enhance contact us page UI.
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100896986/24c79f61-a95a-4e7e-b553-0e09cfeb8aca)
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100896986/1627a0f9-6a51-4cc4-adab-1ab8581567e1)

### Describe the solution you'd like

Solution steps:
I want to remove unwanted space from Contact Us page  & enhance contact us UI.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@vidhimakani74 try to raise any other issue
