### ISSUE TITLE
[New game]: Flappy Bird Game

### ISSUE THREAD

**Issue by Vyshnavi21504** [GameSphere-MultiPlayer/GameSphere#361]
### 🎮 Game Request

The objective of Flappy Bird is straightforward: the player controls a small bird , causing the bird to flap its wings and ascend in height. The goal is to navigate the bird through a series of green pipe obstacles that have openings at different heights. The bird automatically descends over time, so the player must tap at the right moments to keep it airborne and avoid crashing into the pipes.

### Point down the features

Obstacle navigation: The main objective is to navigate the bird through a series of green pipe obstacles. The pipes have openings at different heights, and the player must time their taps to pass through the gaps without colliding.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Vyshnavi21504 This game is already exist, so please try to raise any other issue
