### ISSUE TITLE
[New game] [Insect Catch Game]: 

### ISSUE THREAD

**Issue by JadavShraddha** [GameSphere-MultiPlayer/GameSphere#365]
### 🎮 Game Request

Game logic and basic description
This game is created with the help of html, css and javascript.
In this game first you can choose your favorite insect.The objective of the game is to catch as many insects as possible within a given time limit.
The insects come in various shapesand they move quickly and unpredictably across the screen.
The catchers must be quick and agile to track the insects' movements and snatch them out of the air.

### Point down the features

Game points

change the insect type
show user points and time on screen
sound feature

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@JadavShraddha first properly complete both of task

**Comment by JadavShraddha** [comment]
I completed both the task properly. Now please assign me this task.
