### ISSUE TITLE
[New game]: Add the game of Snake and Water

### ISSUE THREAD

**Issue by Parmesh119** [GameSphere-MultiPlayer/GameSphere#371]
### 🎮 Game Request

This game is a single-player game and the user has to choose one option and based upon that computer will decide who wins the game.

### Point down the features

There is no game points but instead of points the user can understand how to make a simple game and how It is working

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Parmesh119 without assign why did you send PR

**Comment by Durgesh4993** [comment]
Send me a demo vedio if it is good then i'll be merge PR
