### ISSUE TITLE
[New game]: Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by shellyverma** [GameSphere-MultiPlayer/GameSphere#373]
### 🎮 Game Request

Game logic and basic description

Make the tic-tac-toe game using HTML,CSS  and Javascript. 

### Point down the features

1. Two-Players Game
2. Responsive on Desktop, Mobile and Tablet

### Select The Game Type

Multiplayer

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by shellyverma** [comment]
Hey @Durgesh4993 @mahamat-abdelkerim-abakar ,I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23.

**Comment by Durgesh4993** [comment]
@shellyverma This game is already exist so please try to raise any other issue
