### ISSUE TITLE
[New game]: Breakout Game

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#374]
### 🎮 Game Request

This game is a single player game in which user have to hit the block with a ball and and he need to stop the ball to not touch the ground.

### Point down the features

- Single player game
- Easy to play
- Had to hit block with ball
- need to stop the ball to touch with ground

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/525d9447-d41e-42cf-96ac-1d84335a1e0c)

@Durgesh4993  Please assign me this issue

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@lakhan06 This game is already exist, please try to create some multiplayer games
