### ISSUE TITLE
[New game]: Mix and Paint

### ISSUE THREAD

**Issue by Tisha6661** [GameSphere-MultiPlayer/GameSphere#398]
### 🎮 Game Request

Color the object by mixing and making the exact paint color with the given color palette. It is a fun game to play and learn the mixing of primary colors to make secondary colors.

### Point down the features

Game points
Color Mixing: Combine primary colors to create new colors through mixing.
Palette Selection: Choose from a variety of colors on a palette for mixing and painting.
Different Brush: Select different brush for painting with varying thickness.
Canvas Interaction: Interact with a canvas by clicking and dragging the mouse to paint.
Undo/Redo: Provide the ability to undo and redo previous painting actions.
Color Picker: Use a color picker tool to select any color from the canvas or palette.
Eraser Tool: Include an eraser tool to remove specific paint strokes or clear the canvas.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by mahamat-abdelkerim-abakar** [comment]
@Tisha6661 can you share a video or screenshoot  about it ?

**Comment by Tisha6661** [comment]
It would be something like this- 
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98682478/e162f892-5570-4165-bde5-a59eca8d8aae)

Using color palette I've already made-
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98682478/d96015bf-85ef-42f5-92c0-533d5c3c17ba)

**Comment by Tisha6661** [comment]
@Durgesh4993 , @mahamat-abdelkerim-abakar I have made the pull request regarding this game, pleas verify and merge.
