### ISSUE TITLE
[New game]: Flappy bird

### ISSUE THREAD

**Issue by Teddy1404** [GameSphere-MultiPlayer/GameSphere#399]
### 🎮 Game Request

Game logic and basic description
The game is played in a canvas element that represents the game screen.
The player controls a bird, represented by a yellow rectangle, by clicking or tapping on the screen. Each click or tap makes the bird flap its wings and move upwards.

### Point down the features

Game points
The game is made using HTML , CSS and JavaScript .
The bird is affected by gravity, causing it to fall down if not flapping. The player needs to time the flaps correctly to keep the bird airborne and avoid hitting the pipes or the ground.
If the bird collides with any pipe or touches the ground, the game is over.
The player earns a point each time the bird successfully passes through a gap between the pipes without colliding.
The game continues until the bird collides or the player decides to stop playing.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Teddy1404 This game is already exist, so raise any other issue
