### ISSUE TITLE
[New game]: KIll The Bird

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#405]
### 🎮 Game Request

In this game player have to kill the bird using the mouse.

### Point down the features

- Single PLayer
- Time limit
- easy to play
- Need to Shoot  the bird

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/81bf36af-7e51-4b3f-9bcd-ae8dee671641)

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/ab1258c5-f797-41e5-9bc6-09ce4ed51505

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by lakhan06** [comment]
@Durgesh4993  I am writing to kindly request your attention and consideration in reviewing and accepting my pull request. I would greatly appreciate it if you could allocate some time to review the pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.
Thank You

**Comment by Durgesh4993** [comment]
@lakhan06 Yes i have multiple work so please connect with me at linkedIn
