### ISSUE TITLE
[New game]: Rabbit game

### ISSUE THREAD

**Issue by Kalivarapubindusree** [GameSphere-MultiPlayer/GameSphere#414]
### 🎮 Game Request

I want to add rabbit game using html css javascript.
Can you please assign me this task under GSSOC'23.

### Point down the features

Game points

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Kalivarapubindusree Please send a demo vedio

**Comment by Kalivarapubindusree** [comment]
![IMG-20230620-WA0002](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/114821855/d7e70232-b46e-4f24-9cc8-184a3003ac38)
This is the screenshot of the game . If you want vedio also I will send @Durgesh4993

**Comment by Durgesh4993** [comment]
Ok

**Comment by Durgesh4993** [comment]
This game is already exist so please raise any other issue
