### ISSUE TITLE
[New game]: Flappy Bird

### ISSUE THREAD

**Issue by smty2018** [GameSphere-MultiPlayer/GameSphere#426]
### 🎮 Game Request

Want to add a pixelated flappy bird game. Players control a pixelated bird as it flies through a vibrant and challenging environment. The goal is to navigate the bird through narrow gaps between pipes or other obstacles, testing the player's timing and reflexes.

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/74114936/0027461f-38f0-4105-b59c-0f0edc770054)

### Point down the features

Game points:
Points get added on hitting the coin.

Controls:
The spacebar is used to control the bird.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by smty2018** [comment]
@Durgesh4993 please assign me this issue

**Comment by Durgesh4993** [comment]
@smty2018 This game is already exist
