### ISSUE TITLE
[Enhancement]: Addition of a dedicated newsletter section on the homepage.

### ISSUE THREAD

**Issue by chinmayjain08** [GameSphere-MultiPlayer/GameSphere#428]
### Is your enhancement request related to a problem? Please describe.➕

Feature Enhancement : 
We can create a dedicated section for newsletter to make the homepage more appealing to the veiwer/user.
Also it will make the web application more interacting in users perspective.

### Describe the solution you'd like

Solution steps:
We can create a dedicated section for newsletter to make the homepage more appealing to the veiwer/user.
Also it will make the web application more interacting in users perspective.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@chinmayjain08 It is also available in home page

**Comment by chinmayjain08** [comment]
It is in the footer section only.
I wanted to add a proper separate full width newsletter section.
