### ISSUE TITLE
[Enhancement]: Want to improve the ui of home page

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#430]
### Is your enhancement request related to a problem? Please describe.➕

I want to improve the ui of home page 

### Describe the solution you'd like

**Demo Video**

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/9502827c-8485-4d2f-900d-a9bf6c67e657

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Diya1418** [comment]
I would like to work on this issue. Please assign it to me.
