### ISSUE TITLE
[Enhancement]: add sound on clicking the options available on the page 

### ISSUE THREAD

**Issue by NM2025** [GameSphere-MultiPlayer/GameSphere#440]
### Is your enhancement request related to a problem? Please describe.➕

please assign this task to me  . I want to add sound when user click on the options available on the page

### Describe the solution you'd like

Solution steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@NM2025 Could you please send me a example or demo vedio
