### ISSUE TITLE
[New game]: Dungeon Crawler

### ISSUE THREAD

**Issue by Killer2OP** [GameSphere-MultiPlayer/GameSphere#445]
### 🎮 Game Request

# Game logic and basic description
Quickly and easily access a thrilling dungeon-crawling experience at any time. With a simple click of a button, players can enter a fully-realized, randomly generated dungeon filled with monsters and diablo inspired equipment looting system!

### Point down the features

Simple UI Based game of dungeon experience.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Killer2OP Please add a demo or exaample

**Comment by Killer2OP** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/111378171/06aec44a-7c1f-4628-a1a6-65d67cdab7c0
