### ISSUE TITLE
[New game]: Falling Blocks

### ISSUE THREAD

**Issue by thakurdiwakar** [GameSphere-MultiPlayer/GameSphere#448]
### 🎮 Game Request

Game logic and basic description

Falling Blocks is a simple yet addictive game in which players use a platform at the bottom of the screen to catch falling blocks. The goal is to catch as many blocks as possible in order to score as many points as possible.

The game starts with a player-controlled platform in the bottom-center of the screen. Blocks of various shapes and colours begin to fall from the top of the screen at a consistent rate. To collect the falling pieces, the player must move the platform horizontally using the left and right arrow keys (or any other predefined controls).

### Point down the features

Game points:

1.Easy to play
2.Addective
3.Responsive

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

[FallingBlocks.webm](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/76618190/2a4623a8-39d1-4edb-bd8d-a05c76111903)

**Comment by thakurdiwakar** [comment]
please assign this issue to me @Durgesh4993

**Comment by Durgesh4993** [comment]
@thakurdiwakar Please add a demo vedio

**Comment by thakurdiwakar** [comment]
@Durgesh4993 i have added a demo video ,please check
