### ISSUE TITLE
[Bug]: Contact us page not responsive

### ISSUE THREAD

**Issue by gayatriagarwal19** [GameSphere-MultiPlayer/GameSphere#452]
### Give a brief about the bug ✍️

The contact us page is not responsive for mobile screens

![Meet - tyq-qbhy-qjh - Google Chrome 21-06-2023 15_06_28](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98116507/d844c0f3-37cd-492b-baaf-70689d88e307)

### What is the expected behavior? 🤔

The screen should adjust according to the screen width

### Provide step by step information reproduce the bug 📄

Go to the Contact us page and Inspect to view responsive behaviour 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

Please assign me this issue under Gssoc23 @Durgesh4993

**Comment by amilali** [comment]
Please assign me this issue under Gssoc23 @Durgesh4993
