### ISSUE TITLE
[New game]: Duck Hunting Game

### ISSUE THREAD

**Issue by Vyshnavi21504** [GameSphere-MultiPlayer/GameSphere#461]
### 🎮 Game Request

This game is designed to test your shooting skills. The goal of the game is to shoot as many ducks as possible in 30 seconds. 

##DEMO video

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/111994644/c943bbdf-ee86-413b-bb20-2148b5371a2e

### Point down the features

The counter will show you how many targets you hit in the 30s.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Vyshnavi21504 Add a demo vedio

**Comment by Vyshnavi21504** [comment]
@Durgesh4993 I added a demo video

**Comment by Durgesh4993** [comment]
@Vyshnavi21504 Please raise any other issue
