### ISSUE TITLE
[Bug]: Convert Images to WebP Format for Improved GitHub Project Performance

### ISSUE THREAD

**Issue by Avinash905** [GameSphere-MultiPlayer/GameSphere#483]
### Give a brief about the bug ✍️

Currently, the images in our GitHub project are stored in the PNG image format. However, I would like to convert them to the more efficient WebP format. This conversion will help us reduce file sizes while maintaining image quality, leading to improved website performance and faster loading times. This issue aims to update the entire project's image assets from PNG to WebP format.

### What is the expected behavior? 🤔

In order to optimize our project's image assets and enhance user experience, I propose converting all the PNG images to WebP format. WebP is a modern image format that offers superior compression capabilities without compromising visual quality. By leveraging this format, we can significantly reduce file sizes, resulting in faster load times and reduced bandwidth usage.

### Provide step by step information reproduce the bug 📄

- Start by identifying all the PNG images currently present in the project. This includes images used in HTML, CSS, JavaScript, or any other relevant files.

- Utilize image conversion tools or libraries to convert each PNG image to the WebP format. Ensure that the conversion process maintains the original image quality as much as possible.

- Once the images have been converted, update the references to the PNG images in the project's codebase. Replace the references with the corresponding WebP image paths to ensure seamless integration.

- Thoroughly test the project after the conversion process to ensure that all images are displayed correctly and maintain their original quality. Verify that the project's functionality remains intact and that there are no broken image references or display issues.

- Submit a pull request with the changes, making sure to include a clear description of the modifications made, the reasoning behind the conversion, and any relevant performance improvements observed.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Durgesh4993** [comment]
@Avinash905 No need to to update just upload any where and add their link in Website

**Comment by Durgesh4993** [comment]
@Avinash905 Are you able to this work

**Comment by Avinash905** [comment]
> @Avinash905 Are you able to this work

Yes

**Comment by Durgesh4993** [comment]
Nice start work
