### ISSUE TITLE
Need to add Search Bars

### ISSUE THREAD

**Issue by PatilHarshh** [GameSphere-MultiPlayer/GameSphere#494]
### Is your enhancement request related to a problem? Please describe.➕

need to add search bars to search games

### Describe the solution you'd like

Solution steps 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by PatilHarshh** [comment]
@Durgesh4993 please assign it to me

**Comment by Durgesh4993** [comment]
@PatilHarshh Are you able to create a search bar where we are able to search alphabatically

**Comment by PatilHarshh** [comment]
Yes

**Comment by PatilHarshh** [comment]
assign it to me @Durgesh4993

**Comment by PatilHarshh** [comment]
COMPLETED
