### ISSUE TITLE
[New game]: Simon Game

### ISSUE THREAD

**Issue by Soumyajit2825** [GameSphere-MultiPlayer/GameSphere#504]
### 🎮 Game Request

Want to add Simon Game 

### Point down the features

Tech Stack used :-

- HTML
- CSS 
- JS

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by sumitkr2000** [comment]
Can I work on this issue?

**Comment by Durgesh4993** [comment]
@Soumyajit2825 Please send a demo vedio

**Comment by Soumyajit2825** [comment]
![SimonVideo (2)](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100519291/13bec51d-9511-4dd4-800a-b487e58eac20)
@Durgesh4993

**Comment by Durgesh4993** [comment]
This game is already exist
