### ISSUE TITLE
[New game]: Spelling Bee

### ISSUE THREAD

**Issue by vaanyasharmaaa** [GameSphere-MultiPlayer/GameSphere#505]
### 🎮 Game Request

A spelling bee game will typically involve the user being given a word with the help of audio and then they have to attempt to spell it correctly. This game is designed to help players improve their spelling skills while providing an enjoyable and engaging experience.

 After spelling it, you have to click on submit and you will be told if the answer is correct or not.

### Point down the features

* You can ask for a repetition of the audio of the word
* You will be told if answer is correct or not
* You can change the word if you find it difficult 

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@vaanyasharmaaa Please send me a demo vedio

**Comment by vaanyasharmaaa** [comment]
Kindly turn up the volume for better understanding. 
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/130481025/e7e06801-c708-4bee-9932-c8073bb816ff


https://github.com/GameSphere-MultiPlayer/GameSphere/assets/130481025/77bdd3f6-5f08-428b-ac35-c9b1a817b614

Hope you like it
Thanks & Regards

**Comment by vaanyasharmaaa** [comment]
@Durgesh4993 sir, kindly assign me this issue under GSSOC'23
