### ISSUE TITLE
[New game]: Alphabets

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#512]
### 🎮 Game Request

The Game features a user interface that displays all the alphabets from A to Z, accompanied by corresponding images. When a child clicks on a specific alphabet or types a single alphabet, a corresponding sound is played. For example, if the child clicks on the letter 'A', a sound saying "A for apple" will be played.

### Point down the features

The purpose of this Game is to provide a fun and educational tool for children to learn and familiarize themselves with the alphabet. By associating each letter with a visual representation and an auditory cue, it aims to enhance their understanding and retention of the alphabet.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@shraddha761 Please send me a demo vedio

**Comment by shraddha761** [comment]
> @shraddha761 Please send me a demo vedio

I has send you in discord

**Comment by shraddha761** [comment]
> @shraddha761 Please send me a demo vedio
I had send you video at discord please see there
