### ISSUE TITLE
[New game]: Mario Matching Game

### ISSUE THREAD

**Issue by BidisaChowdhury** [GameSphere-MultiPlayer/GameSphere#517]
### 🎮 Game Request

The game board consists of multiple tiles, each containing an image. This game challenges players to match three identical images.

### Point down the features

1)It is very easy to play.
2)Click on each part and complete the puzzle.
3)If players don't get it, simply they can click on Reset Game and try again!

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by soorjya** [comment]
i can help you for creating this game so please do assigne me this task under GSSOC ' 23
