### ISSUE TITLE
[New game]: Valorous Rabbit Game - 3D

### ISSUE THREAD

**Issue by abhinav-m22** [GameSphere-MultiPlayer/GameSphere#523]
### 🎮 Game Request

I want to add a new project using HTML, CSS and JavaScript which is a 3D game of a rabbit and a monster.

### Point down the features

1. The monster chases the rabbit and as a user you have to control the rabbit and save yourself from the monster.
2. The rabbit jumps on click of the mouse and saves from the obstacles.
3. The game also has sound effects to provide a seamless experience to the user.
4. Overall 3D experience will be included along with levels.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by abhinav-m22** [comment]
@Durgesh4993 @Aman1-coder @mahamat-abdelkerim-abakar 
Please assign me the issue

**Comment by abhinav-m22** [comment]
@Durgesh4993 Please assign me this issue!

**Comment by soorjya** [comment]
i can help you for creating this game so please do assigne me this task under GSSOC ' 23

**Comment by Durgesh4993** [comment]
@abhinav-m22 This game is already exist
