### ISSUE TITLE
[New game]: Guess the Random Shape

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [GameSphere-MultiPlayer/GameSphere#524]
### 🎮 Game Request

Game logic and basic description

- Created using HTML, CSS and JS
- Random shapes are generated using dots.
- Before completely filling of the shape using dots, guess the shape

### Point down the features

Game points

- (+1) for correct answer
- 0 for the wrong answer
- There will be 3 lives, If all lives are exhausted, you will lose the game

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@Durgesh4993 @Aman1-coder @mahamat-abdelkerim-abakar please assign this game to me to contribute under GSSoC'23 program

**Comment by Durgesh4993** [comment]
Please send a demo vedio

**Comment by Avdhesh-Varshney** [comment]
Demo video

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/114330097/ca6a1c2f-551c-47ba-a52d-6533f661eb6f

@Durgesh4993 Please assign this project to me to create a pull request under GSSoC'23 program
