### ISSUE TITLE
New Game: Pig Game

### ISSUE THREAD

**Issue by Hypertext-Workaholics** [GameSphere-MultiPlayer/GameSphere#53]
By using html ,css and js I will create this game. Please assign me this

**Comment by Durgesh4993** [comment]
@Hypertext-Workaholics could you please explain more, and also tell it is multiplayer game or not if not so please to create a multiplayer game

**Comment by soorjya** [comment]
I want to add pig game  in website .Please assign this issue to me under GSSOC'23
