### ISSUE TITLE
search box

### ISSUE THREAD

**Issue by mandliyarajendra11** [GameSphere-MultiPlayer/GameSphere#539]
### Is your enhancement request related to a problem? Please describe.➕

we can add search box for searching game

### Describe the solution you'd like

-

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
This task is already assigned
