### ISSUE TITLE
[New game]: Number Sliding Puzzle Game [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [GameSphere-MultiPlayer/GameSphere#548]
### 🎮 Game Request

Game logic and basic description

- This game is a single player game.
- The Number Sliding Puzzle Game is a classic puzzle where players rearrange numbered tiles on a square grid.
- The objective is to arrange the tiles in ascending order, starting from a randomized initial configuration.
- Players can slide tiles into the empty space, strategically planning their moves to achieve the desired order.
- The challenge lies in the limited moves available, requiring logical thinking and problem-solving skills.

### Point down the features

Game points

- Complete the game and win the game.
- Congrats with a grand celebration look of the website on completion of the game.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@Durgesh4993 @Aman1-coder @mahamat-abdelkerim-abakar 
Please assign this project to me to work on it and give a valuable contribution under GSSoC'23 program

**Comment by Durgesh4993** [comment]
@Avdhesh-Varshney could you please Send a demo vedio
