### ISSUE TITLE
[New game]: Nokia3310-Snake Master 

### ISSUE THREAD

**Issue by thakurdiwakar** [GameSphere-MultiPlayer/GameSphere#553]
### 🎮 Game Request

**Game logic and basic description**

A classic Snake game inspired by the popular Nokia 3310 mobile phone. It is implemented using HTML, CSS, and JavaScript. The game is played on a grid-based layout where the player controls a snake using the arrow keys. The objective is to guide the snake to eat apples that randomly appear on the grid, which makes the snake grow longer. However, the player must be careful not to let the snake collide with the boundaries of the grid or its own body, as that would result in a game over.
The game features a start/restart button to begin or restart the gameplay. The score is displayed, indicating the number of apples eaten by the snake.

### Point down the features

Game points:

1.High Score Tracking
1.Easy to play
2.Addective
3.Responsive

**Demo Video:**

[Nokia3310-Snake Master.webm](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/76618190/c67ec8db-886e-4070-9a70-71d1b752a420)

The Video is in 2x speed

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@thakurdiwakar Try to raise any other issue
