### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by Swapnil-2503** [GameSphere-MultiPlayer/GameSphere#557]
### 🎮 Game Request

Game logic and basic description

A multiplayer game where players take turns guessing the country based on its flag.

### Point down the features

Game points

1. The game will display a flag image.
2. Player 1 enters the name of the country they think the flag belongs to in the input field.
3. Player 1 clicks the **Submit** button to check their guess.
4. If Player 1's guess is correct, they will receive a congratulatory message.
5. If Player 1's guess is incorrect, they will be informed of the correct country.
6. Player 1 clicks the **Next** button to proceed to the next flag.
7. Player 2 then takes their turn by following steps 2-6.
8. The game continues with players taking turns guessing flags.
19. Enjoy playing and challenge each other to see who can guess the most flags correctly!

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Swapnil-2503 could you please Send a demo vedio

**Comment by Swapnil-2503** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/89910173/cc69c9ff-af59-45b3-b7c0-9dfc94157104
