### ISSUE TITLE
[New game]: Throw 'n' Score - Multiplayer game (GSSOC'23)

### ISSUE THREAD

**Issue by srujana-16** [GameSphere-MultiPlayer/GameSphere#558]
### 🎮 Game Request

Throw 'n' Score is a dice rolling game where two players compete to reach a total score of 100 or more points. Each player takes turns rolling a dice and has the option to either hold their current score or continue rolling to add more points. The game is designed to be simple and engaging, offering a mix of strategy and luck.

### Point down the features

- Interactive gameplay that allows players to make decisions on each turn.
- Randomized selection of the first player to add an element of unpredictability.
- Clear display of each player's current and total scores.
- Intuitive user interface for easy understanding and enjoyment.

### Select The Game Type

Multiplayer game

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@srujana-16 This game is already exist
