### ISSUE TITLE
[Documentation Bug]: Add table of contents for Multiplayer games

### ISSUE THREAD

**Issue by srujana-16** [GameSphere-MultiPlayer/GameSphere#562]
### Describe the bug ✍️

There is no table of contents for Multiplayer games, it is only present for single-player games. Hence there is no option to navigate to the multiplayer games from the README.md. 

### Provide step by step information reproduce the bug 📄

I would like to add a table of contents for all the Multiplayer games so far. So that from now on whenever a multiplayer game is added the user the update this table to add their folder link. 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@srujana-16 There are only 5 multiplayer game, so try to raise any other issue
