### ISSUE TITLE
[New Feature]: Add Search Functionality on the Website⬇️

### ISSUE THREAD

**Issue by arcVaishali** [GameSphere-MultiPlayer/GameSphere#563]
### Is your enhancement request related to a problem? Please describe.➕

# FEATURE-
Though the Readme of this Repository has a **List of Available games** but since the **number of games** added has increased and will **continue to increase in due course of time**, it is necessary that the [GameSphere Webpage](https://gamesphere-multiplayer.github.io/GameSphere/) should advance in feature and contain a section that consists of -

- **Search Bar** to search on the website itself if the project which user wants to add is present beforehand in the repo. In this way there will also be no unnecessary and redundant Issue be generated and will be good for user to search games he/she likes.

# *Why is it necessary?*
Adding List of Games already available to the Readme makes the ReadMe unreadable as the size of repo increases. It would be better to add a Search Bar functionality to Search similar/existing games.
I am going to add the search bar below the **Top Popular Games Heading** as shown below-

<img width="926" alt="search-functionality-gamesphere" src="https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98754461/4c2de5a9-1e27-4702-a2cd-128bed13854f">

I am going to use front-end web tech tools for creating search interface along with a search library like Elastic Search or Algolia to implement the functionality of search bar. **@Durgesh4993**  Kindly assign me this issue under GSSoC'23 label.

### Describe the solution you'd like

I am going to use front-end web tech tools for creating search interface along with a search library like Elastic Search or Algolia to implement the functionality of search bar. **@Durgesh4993**  Kindly assign me this issue under GSSoC'23 label.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@arcVaishali Sorry but this task is already assigned
