### ISSUE TITLE
[New game]: Color Matcher

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#564]
### 🎮 Game Request

- Color Matcher is a single-player game application coded in HTML, CSS and JavaScript.
- You can play it using only your Left Mouse Button!

### Point down the features

- The application is a simple Matching type game that can be played by a single-player.
- The player can play the game using the Mouse, you only just need to use the Left Mouse Button to play the game.
- The gameplay is very simple. All you have to do is match the same colored tiles within 30 seconds.
- Each color you match will disappear and you to need to proceed to other colors.
- Try to match all the colors before the time runs out.
**Screenshot**
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/808123d3-ff21-43ec-a807-0baeb7bbe92b)
**Demo Video**

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/de9fe889-05de-4201-9113-fdd9e1ee1d0c

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by lakhan06** [comment]
@Durgesh4993  I am writing to kindly request your attention and consideration in reviewing and accepting issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

**Comment by Durgesh4993** [comment]
@lakhan06 Please raise any other issues

**Comment by Durgesh4993** [comment]
@lakhan06 I have a work for you, as you see there are some errors are occured in game page could you please resolve it

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98798977/3642f761-016f-41ca-9101-9a9e586a2f93)

**Comment by Durgesh4993** [comment]
Raise a issue

**Comment by lakhan06** [comment]
@Durgesh4993 Please reopem this and assign me if it is not in the website

**Comment by Durgesh4993** [comment]
@lakhan06 I think so you are able to create some big game, so please raise any big issues
