### ISSUE TITLE
[New game]: pig_game

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#565]
### 🎮 Game Request

Pig is a simple two player dice game.

### Point down the features

If the player rolls a 1, their current score gets zeroed and the other player takes turn.
If the player rolls any other number, it is added to their current score and the player's turn continues.
If a player chooses to "hold" the current score, their turn total is added to their score and the other player takes turn.
The first player to score 100 or more points wins

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@shraddha761 Please send me a demo vedio

**Comment by shraddha761** [comment]
> @shraddha761 Please send me a demo vedio

I had send you at discord please see there. video is big that's why unable to send here
