### ISSUE TITLE
Dockerize project

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#566]
### Describe your question or ask for support.❓

We can create a docker file for a project

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@shraddha761 Could you please send me a demo vedio

**Comment by shraddha761** [comment]
> @shraddha761 Could you please send me a demo vedio

Actually I mean to create a docker file for project which help to you to package your application and its dependencies into a container, making it highly portable. The Docker image can be run on any system that supports Docker, ensuring consistent behavior across different environments. It allow you define the exact steps needed to build your application environment. By versioning your Dockerfile, you can reproduce the exact same environment at any point in the future. This helps avoid "it works on my machine" issues and facilitates collaboration among team members.
