### ISSUE TITLE
[New game]: Rock_Paper_Scissors 

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#568]
### 🎮 Game Request

- It is a Single Player Rock Paper Scissors game
- User can choose one among Rock Paper or Scissors
- Once selected, there's some gestures and then the bot also randomly selects one

### Point down the features

The number of guesses made by the user is displayed.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@shraddha761 This game is already exist
