### ISSUE TITLE
[New game]: BreakOut game

### ISSUE THREAD

**Issue by Aryan5464** [GameSphere-MultiPlayer/GameSphere#569]
### 🎮 Game Request

# **Breakout** 

---

<br>

## **Description 📃**
The objective of the game is to use the paddle to bounce the ball towards the bricks and destroy them. You win when all the bricks are destroyed. But if the ball falls below the paddle into the fiery pits of doom, you lose the game. The paddle has "zones" which bounce the ball in different angles. Try out the game and you will notice it. If the ball bounces at the center, it goes straight up. As it goes to the sides, it's angle and speed increase. This gives you a certain degree of control over the direction of the ball.

<br>

## **How to play? 🕹️**
- The game will start with ball at the center.
- Your role is to use the paddle at the bottom and hit the ball, so that the ball hits and smashed the bricks on the top.
- Try not to let the ball touch the ground; if happens so, then will you lose the game.
- If all the bricks are smashed then you Win!

### Point down the features

Game points

## **functionalities 🎮**
- Left Arrow: Move paddle left. 
- Right Arrow: Move paddle right.

## Screenshots 📸📸

![Screenshot 2023-06-24 171732](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/111825539/fd4071cd-e4e8-4c66-a3e5-d92395b7594e)
![Screenshot 2023-06-24 171709](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/111825539/aa140880-90f4-4765-b4a5-175951963b84)

## Working video 🎥📹

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/111825539/4e4e3a04-801f-415f-8c49-dea958888dfe

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Aryan5464 This game is already exist, if you want to improve then go ahead

**Comment by Aryan5464** [comment]
@Durgesh4993 
* The movements of the game I am adding are smooth and responsive, and the new features I've added make it more fun and challenging to play. I'm really excited to share it with everyone.
* The speed of the increases with time.
* It's difficult for me also to clear the game..
* Please assign me the game.
