### ISSUE TITLE
[New game]: Lonely_Phantom

### ISSUE THREAD

**Issue by Aryan5464** [GameSphere-MultiPlayer/GameSphere#572]
### 🎮 Game Request

# **Lonely_Phantom** 

---

<br>

## **Description 📃**
- You are a lonely phantom in a dark cave.
- Avoid spikes and holes by jumping while light wheakens.
- Collect diamonds to buy upgrades to survive longer and longer, Enjoy!

## **How to play? 🕹️**
- Controls
    * R = Reset stage
    * Escape = Return to menu

- Characters
    * Arrow keys = Move
    * Down arrow = Enter door / Toggle switch
    * X = Attack

<br>

## **Screenshots 📸**

<br>

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/111825539/108bf6a6-211d-4868-b8df-7cf0c8de9594)

### Point down the features

Game points

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryan5464** [comment]
This game is ready to be merged, If you want I can send you the video too.

**Comment by Durgesh4993** [comment]
Ok , send me a PR
