### ISSUE TITLE
[Bug]: Error in Game Page

### ISSUE THREAD

**Issue by lakhan06** [GameSphere-MultiPlayer/GameSphere#573]
### Give a brief about the bug ✍️

There is error in game page so i want to resolve it and i also can add reveal effect in game page

### What is the expected behavior? 🤔

Bottom cards are not properly align and their is over flow.so they need to be fixed

### Provide step by step information reproduce the bug 📄

@Durgesh4993 asign this issue to me

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@lakhan06 Sorry this issue is resolved by any other contributer

**Comment by lakhan06** [comment]
ok @Durgesh4993 then please asign me the game the i requested previously if it is not in the website
