### ISSUE TITLE
[New game]: Rock Paper Scissors multiplayer game - GSSOC'23

### ISSUE THREAD

**Issue by srujana-16** [GameSphere-MultiPlayer/GameSphere#575]
### 🎮 Game Request

Game logic and basic description
The classic Rock, Paper, and Scissors game is built using HTML, CSS, and Javascript. It's a multiplayer game engaging two players at a given time.

### Point down the features

- Only two users can play at the same time.

- Both players pick either rock, paper or scissors.

- After the players make their selection, the game will tell them whether a tie occurred or if one player defeated the other.

- The game will track each player's wins and losses.

- Some chat functionality is created here to enable the ususal taunts and insults from jerk opponents

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@srujana-16 send me a demo vedio
