### ISSUE TITLE
[New Feature]: website requires Preloader 

### ISSUE THREAD

**Issue by yashpreet2707** [GameSphere-MultiPlayer/GameSphere#582]
### Describe your question or ask for support.❓

the website takes a bit of time to load, so I suggest we should add a *preloader* to the website.

Please assign me this issue under Gssoc'23 contributor.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@yashpreet2707 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer
