### ISSUE TITLE
[New game]: Slingshot game

### ISSUE THREAD

**Issue by Kalivarapubindusree** [GameSphere-MultiPlayer/GameSphere#585]
### 🎮 Game Request

I want to add slingshot game using html,css,javascript.
can you please assign this task under gssoc'23 @dur

### Point down the features

Game points

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Kalivarapubindusree send a screenshort

**Comment by Kalivarapubindusree** [comment]
![WhatsApp Image 2023-06-25 at 7 36 41 PM (1)](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/114821855/0c188a95-d972-4c54-87bc-8b5906b48b9b)

This is the screenshot of my game @Durgesh4993
