### ISSUE TITLE
[New game]: Ravoucs Raven Run

### ISSUE THREAD

**Issue by Nishitbaria** [GameSphere-MultiPlayer/GameSphere#596]
### 🎮 Game Request

"Raucous Raven Run" is an endless running game where players control a brave bird flying through the sky, attempting to avoid a flock of mischievous ravens. The game features smooth gameplay, comical animations, a variety of ravens with different sizes and colors, and an enjoyable soundtrack. Players must dodge and maneuver skillfully to avoid colliding with the ravens and earn a high score. Getting hit by a raven triggers amusing and explosive animations, adding an extra layer of entertainment to the game.

Adding "Raucous Raven Run" to the Gamesphere Project would enhance the diversity of available games and provide users with a fun and lighthearted gaming experience.

### Point down the features

Game points
Features
-Smooth gameplay
-Comical animations
-Variety of ravens
-Soundtrack

![Informatician and 4 more pages - Personal - Microsoft​ Edge 27-06-2023 20_27_06](https://github.com/kunjgit/GameZone/assets/85815172/3a24aa55-02a8-4036-b23c-e894c34f9b12)

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Nishitbaria** [comment]
Hey **@Durgesh4993** please assign me to this issue

**Comment by Aman1-coder** [comment]
@Nishitbaria 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer
