### ISSUE TITLE
[Bug]: Game Section Issue

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [GameSphere-MultiPlayer/GameSphere#602]
## Description
Issue in the Game Section due to miss code attachment there is a issue occur in the Game Section.
### Video -
[Screencast from 26-06-23 01:30:45 AM IST.webm](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/121503426/4af9e14e-eac8-4c46-a42f-fcf71cc83421)

## Behavior -
It should be access the games in a proper manner but it's overlapping the games.

### Provide step by step information reproduce the bug 📄

It's a overlapping issue so it can be fixed using the proper alignment of the website using HTML & CSS

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@SyedImtiyaz-1 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer
