### ISSUE TITLE
[New game]: Escape Room

### ISSUE THREAD

**Issue by sabhisharma-ise** [GameSphere-MultiPlayer/GameSphere#604]
### 🎮 Game Request

It is a puzzle game where you must solve a series of puzzles in order to escape the room. The puzzles are all based on different programming concepts, such as HTML, CSS, and JavaScript.

### Point down the features

Challenging puzzles: The puzzles in the game are designed to be challenging, but they are also fair. If you get stuck, you can always ask for help from the community.
Educational: The puzzles in the game are based on different programming concepts, such as HTML, CSS, and JavaScript. This makes the game a great way to learn about these concepts.
Visually appealing: The game is visually appealing and engaging. The puzzles are presented in a way that is both challenging and fun.
Social: The game has a forum where you can discuss the puzzles with other players. This is a great way to get help if you are stuck, or to share your own solutions.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@sabhisharma-ise 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer
