### ISSUE TITLE
[New game]: Stacker game

### ISSUE THREAD

**Issue by sabhisharma-ise** [GameSphere-MultiPlayer/GameSphere#605]
### 🎮 Game Request

Stacker game uses just html and css, at every level a group of boxes moves on a 10x10 grid.

### Point down the features

Have to catch the speed of the boxes which are moving and have to freeze them at our desired place. This game's goal is to challenge the speed of player's vision and skills to make to the top of the stack.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@sabhisharma-ise 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by Durgesh4993** [comment]
Send a demo vedio

**Comment by sabhisharma-ise** [comment]
@Durgesh4993 Here you go!

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100849696/28972c2d-1c66-49af-9845-5642e828f043
