### ISSUE TITLE
[New game]: Fifteen Puzzle game - GSSOC'23

### ISSUE THREAD

**Issue by srujana-16** [GameSphere-MultiPlayer/GameSphere#609]
### 🎮 Game Request

The Fifteen Puzzle is a classic sliding puzzle game where the goal is to rearrange the tiles in numerical order by sliding them into the empty space. This implementation of the game is built using HTML, CSS, and JavaScript.

### Point down the features

- The game consists of a 4x4 grid with fifteen numbered tiles and one empty space.
- To make a move, click on a tile adjacent to the empty space. The clicked tile will slide into the empty space.
- The goal is to arrange the tiles in numerical order, from 1 to 15, starting from the top-left corner and leaving the bottom-right cell empty.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@srujana-16 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer
