### ISSUE TITLE
[New game]: Flying Block

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#612]
### 🎮 Game Request

In this game Control a block and see how long you can survive

### Point down the features

Assign this issue to me

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@shraddha761 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer
