### ISSUE TITLE
[New game]: Anime-Clicker

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#613]
### 🎮 Game Request

Fully functional anime clicker

### Point down the features

Save and load the game if you need to go to sleep for the day, you can come back and your progress will not be erased

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@shraddha761 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by shraddha761** [comment]
@Aman1-coder please assign this issue

**Comment by Aman1-coder** [comment]
@shraddha761 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer
