### ISSUE TITLE
[Enhancement]: Add features to 2048 game Single Player

### ISSUE THREAD

**Issue by palakag29** [GameSphere-MultiPlayer/GameSphere#617]
### Is your enhancement request related to a problem? Please describe.➕

When the page loads, only the game name and start new game button is shown.
When the button is clicked, the board and score field is shown.

### Describe the solution you'd like

2048 game

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@palakag29 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer
