### ISSUE TITLE
[Documentation Bug]: No contributing-guideline.md and code-of-conduct.md file

### ISSUE THREAD

**Issue by palakag29** [GameSphere-MultiPlayer/GameSphere#618]
### Describe the bug ✍️

There is no contributing-guideline.md and code-of-conduct.md file

### Provide step by step information reproduce the bug 📄

I would like to make a contributing-guidelines file and code-of-conduct.md file and contribute it to this project.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@palakag29 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by bhavya1857** [comment]
yes, please assign her @Aman1-coder

**Comment by Durgesh4993** [comment]
@palakag29 it is added on gihub folder

**Comment by palakag29** [comment]
@Durgesh4993 there is no file . please check

**Comment by palakag29** [comment]
@Durgesh4993 when we click the link to Contributing guideline. it shows us error

> ### Describe the bug ✍️
> There is no contributing-guideline.md and code-of-conduct.md file
> 
> ### Provide step by step information reproduce the bug 📄
> I would like to make a contributing-guidelines file and code-of-conduct.md file and contribute it to this project.
> 
> ### Select program in which you are contributing
> GSSoC23
> 
> ### Code of Conduct
> * [x]  I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/112793075/7acde012-af5a-47a4-baf8-323ca470c1df)

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98798977/bf5ff538-546b-4fba-94cc-06c405645ec2)
