### ISSUE TITLE
[Bug]: Search Button is not visible

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [GameSphere-MultiPlayer/GameSphere#630]
### Give a brief about the bug ✍️

- Description -
Search button is not visible in the `Games` Section
### What is the expected behavior? 🤔

- Description-
The search section should be align in a proper ratio.

### Bug Screenshot -
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/121503426/745d605d-91a4-4824-9636-658a9694475c)

It can be fixed using the css and html and I think there is no width on the search section that's why it's looking like this 👍🏻 

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by SyedImtiyaz-1** [comment]
@Durgesh4993 ,
Review this 👍🏻

**Comment by Durgesh4993** [comment]
@SyedImtiyaz-1 no please check out this issue is already solved
