### ISSUE TITLE
[Feature Request]: `openAI GPT` - Chatbot

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [GameSphere-MultiPlayer/GameSphere#631]
### Describe your question or ask for support.❓

Hey @Durgesh4993   ,
Adding GPT v3.5 {Chat Bot} 👍🏻 
But you have to add your own API from Chat-GPT bcz API is a personal token (key) and I'll also add a cloumn for that in the code so you just have to paste the API and it will run for  you. 

### How to get GPT - API ?
I'll drop the instructions while raise a PR
& I'll add a Step to get API while raising a `PR` 👍🏻 
- Working on this 💯 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@SyedImtiyaz-1 could you please explain more

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 could you please explain more

It's a Chat Bot with uses API to fetch data from the **Chat GPT** and this cahtbot gives reply on the run time and ans all the question also it will help GameSphere website to increase the User experience 👍🏻
