### ISSUE TITLE
[New game]: Crack-The-Code

### ISSUE THREAD

**Issue by pavitrachavda97** [GameSphere-MultiPlayer/GameSphere#638]
### 🎮 Game Request

Game logic and basic description
- A player has to guess the 3 numbers in order to win this game by using 5 simple hints. If player guess it correct than player will win else game restarted.

### Point down the features

Game points
- Generate 3 number code
- Provide hints
- Player's guess
- Submit guess
- Check for correct submission
- If true win else loss
- Loop continues

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@pavitrachavda97 this game is already exist, so please raise any other issue
