### ISSUE TITLE
Adding a Updated version of Chat GPT Chat Bot

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [GameSphere-MultiPlayer/GameSphere#658]
### Feature Request
Hey @Durgesh4993 ,
Will work properly this  time assign me this issue previously you reverted my PR.

Adding GPT v3.5 {Chat Bot} 👍🏻 
But you have to add your own API from Chat-GPT bcz API is a personal token (key) and I'll also add a cloumn for that in the code so you just have to paste the API and it will run for  you. 
### How to get GPT - API ?
- I'll drop the instructions while raise a PR
- & I'll add a Step to get API while raising a `PR` 👍🏻 
- Working on this 💯 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@SyedImtiyaz-1 Please copy new codes not old codes

**Comment by SyedImtiyaz-1** [comment]
Done but previously you gave me level 2.
If you don't mine can you promote this issue to level 2 ?
