### ISSUE TITLE
[New game]: Circus charly

### ISSUE THREAD

**Issue by linga66** [GameSphere-MultiPlayer/GameSphere#669]
### 🎮 Game Request

One of the most common obstacles in Circus Charlie is the fire ring. These rings are located throughout the levels and Charlie must jump over them to avoid being burned. Another common obstacle is the ring of death. This ring is located at the end of each level and Charlie must jump through it to complete the level.
If Charlie gets hit by fire, he will lose a life. If he falls off the lion, he will also lose a life. The game ends when Charlie loses all of his lives.

### Point down the features

Circus Charly is another most popular Console Game in which the character is on the running Lion and we have to make the lion jump without getting collided with the Fire and Ring.

Assign me this

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@linga66 Send a demo vedio

**Comment by linga66** [comment]
https://drive.google.com/file/d/1F3mDtd00SLDNPrRz2JWVHLySguUljTaO/view?usp=sharing
