### ISSUE TITLE
[New game]: othello/reversi

### ISSUE THREAD

**Issue by RitiChandak** [GameSphere-MultiPlayer/GameSphere#677]
### 🎮 Game Request

Game logic and basic description

The game starts with an 8x8 board with two initial black and two initial white pieces placed in the center.
Players take turns placing their colored pieces on the board. A move is valid if it results in the flipping of at least one opponent's piece in a straight line (horizontally, vertically, or diagonally).
some of the features are :
-to flip the token
-cascading effects
-the corners and edges of the board have special strategic significance in Othello

### Point down the features

Game points
The features that make Othello a compelling and engaging game are that it combines tactical decision-making, spatial awareness, and the ability to adapt to changing board conditions.

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@RitiChandak Send a demo vedio

**Comment by RitiChandak** [comment]
Hello @Durgesh4993 , I won't be able to provide the video at the moment. Would it be fine if I upload it by Tuesday?

**Comment by RitiChandak** [comment]
hey @Durgesh4993 the video is ready should i upload it??
