### ISSUE TITLE
[New game]: Basketball Game

### ISSUE THREAD

**Issue by linga66** [GameSphere-MultiPlayer/GameSphere#689]
### 🎮 Game Request

Test your shooting skills and aim to score as many baskets as possible within a time limit. Adjust your shot angle and power, beat your high score, and immerse yourself in the dynamic gameplay.

### Point down the features

Animated Sprites after making three shots in a row
Shot power based on time, trajectory based on indicated angle

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@linga66 this game is already exist please raise any other issue
