### ISSUE TITLE
To add a multiplayer Dice game 

### ISSUE THREAD

**Issue by ayan-joshi** [GameSphere-MultiPlayer/GameSphere#690]
### 🎮 Game Request

It will be a two player game.
If the player gets 1 in dice then he lose his chance ,
the dice value will be added to the current score every time you role the die.
Then Hold is used to hold your current score and add it to Total Score,
If the total score is 100 or more then U are the winner.

So this is a proper description of a simple game.

### Point down the features

Technology used will be :- 
HTML
CSS
JavaScript

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@ayan-joshi send a demo vedio

**Comment by ayan-joshi** [comment]
@Durgesh4993 surely I'll share today itself

**Comment by ayan-joshi** [comment]
https://www.loom.com/share/fb3782aa445f442aa5c78c774cc8183f?sid=dd2fcbe9-3d05-460e-8430-16235939324d

so this is a video link 
and as explained when 1 comes in the dice the chance is given to the second player and the score is counted 
and when one of player reaches 100 points first he's the winner of the game .

**Comment by Durgesh4993** [comment]
@ayan-joshi This game is already exist, raise any other issue
