### ISSUE TITLE
[New game]: Block Ninja game

### ISSUE THREAD

**Issue by saikiranreddy201** [GameSphere-MultiPlayer/GameSphere#697]
### 🎮 Game Request

Block Ninja is a thrilling slicing game where you become a ninja warrior and slice floating blocks with precision. Test your reflexes, slice through blocks, and aim for high scores. Sharpen your blade and become the ultimate Block Ninja champion!
Even one miss of a block results in a game over.

### Point down the features

The user gets points when he correctly slices a block
He loses the game if he misses it.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@saikiranreddy201 send a demo vedio
