### ISSUE TITLE
[FEATURE]: Smooth Scrolling in website

### ISSUE THREAD

**Issue by Killer2OP** [GameSphere-MultiPlayer/GameSphere#701]
# Details 
Hey, I want to make some improvements to the code and added a smooth scroll feature that provides users with a seamless navigation experience when clicking on links in the navigation bar. I believe this enhancement would greatly benefit the project. Therefore, I kindly request you to assign me this issue.

Assign me this issue under GSSoC'23

**Comment by Killer2OP** [comment]
@Durgesh4993 Can you assign me this issue.

**Comment by Durgesh4993** [comment]
@Killer2OP could you please explain more if you have any example
