### ISSUE TITLE
Addition of scribble game 

### ISSUE THREAD

**Issue by linga66** [GameSphere-MultiPlayer/GameSphere#702]
### 🎮 Game Request

Game logic and basic description
Scribble is a multiplayer draw and guess game. It is insipired Draw My Thing game.

### Point down the features

Game points
Multiple players can play this game
One of the person need to draw the word choosen by him
And all other player need to guess the word
The score will be provided 

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@linga66 send me a demo vedio

**Comment by linga66** [comment]
![1_8IM2UjfGbHms2jy71Q9qmg](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/103192975/4122ffda-1be3-4d93-a4f6-f1a37c51948d)

**Comment by linga66** [comment]
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/103192975/01ed69c5-a365-4f05-b0f7-1f4659281b34)
