### ISSUE TITLE
[Bug]: Bug on games page

### ISSUE THREAD

**Issue by sumitkr2000** [GameSphere-MultiPlayer/GameSphere#706]
### Give a brief about the bug ✍️

Hey, there is a bug on the games page where after certain games the layout is distorted. I have attached the ss of the same. Please assign me this issue so that I can fix it. Thank you!

### What is the expected behavior? 🤔

Consistent layout throughout the page.

### Provide step by step information reproduce the bug 📄

Fix the styling of cards.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@sumitkr2000 This task is assign to anyone else please raise any other issue
