### ISSUE TITLE
[New game]: OTHELLO

### ISSUE THREAD

**Issue by prashanth772** [GameSphere-MultiPlayer/GameSphere#708]
### 🎮 Game Request

Game logic and basic description

Title: Othello - Two-Player Strategy Board Game

The objective of Othello is to have the most disks of your color on the board when the game ends. The game concludes when no more legal moves can be made or when the entire board is filled with disks. The player with the majority of disks on the board at the end of the game is declared the winner.

Gameplay Mechanics:
Players take turns placing one disk of their color on the board. A disk can only be placed on a valid empty square that, when placed, will create a line (horizontal, vertical, or diagonal) of the opponent's disks between the newly placed disk and the player's previously placed disks. When such a line is created, all the opponent's disks in that line are flipped to the player's color. If a player has a valid move available, they must make a move; otherwise, they must pass their turn.

### Point down the features

Once the game ends, the final score is determined by counting the number of disks of each color on the board. The player with the highest score, indicating the most disks of their color, wins the game.

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@prashanth772 send a demo vedio

**Comment by prashanth772** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/124067333/cddc38cf-ffb4-4aed-9b8f-6fe0837ef440
