### ISSUE TITLE
[Question]: Why plagiarised work is accepted 

### ISSUE THREAD

**Issue by Killer2-O** [GameSphere-MultiPlayer/GameSphere#711]
### Describe your question or ask for support.❓

https://github.com/GameSphere-MultiPlayer/GameSphere/pull/687 is copied from https://github.com/ShashwatNigam99/Subway-Surfers

https://github.com/GameSphere-MultiPlayer/GameSphere/pull/671 is copied from https://github.com/zeyu2001/chess-ai

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Killer2-O Thank you for you information
