### ISSUE TITLE
[Question]: DarkMode

### ISSUE THREAD

**Issue by shraddha761** [GameSphere-MultiPlayer/GameSphere#718]
### Describe your question or ask for support.❓

Change to dark button should be there in website
Assign this issue to me under GSSOC'23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@shraddha761 This website is already based on dark theam

**Comment by Durgesh4993** [comment]
if you want to suggest any changes please explain in detail

**Comment by shraddha761** [comment]
@Durgesh4993 yup but to change in light themes also as of now there is icon which change icon colour not colour of website

**Comment by Durgesh4993** [comment]
If you have any good change then go ahead, But before sending PR send me a demo vedio for varification and don't forget to copy latest code
