### ISSUE TITLE
[NEW GAME]: Magic match

### ISSUE THREAD

**Issue by Parul1606** [GameSphere-MultiPlayer/GameSphere#765]
## Description

I would like to add Memory magic match game to the project.
A grid of cards is displayed on the game board, typically faced down at the beginning of the game.
Each card has a matching pair in the grid. The objective is to find and match all pairs of cards.
Players can click or tap on a card to reveal its face.
Please assign me this project I would like to work on it under gssoc.

## Screenshot Section

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/80768852/4a35b9b6-317d-4858-a690-f8c078b228ae)

## Task

- [ ] Follow Us On social media -
- [✅]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [✅]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [✅]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [✅]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Manish12-verma** [comment]
hey,please assign this issue to me, I also want to contribute  in it.
