### ISSUE TITLE
Planet defense game

### ISSUE THREAD

**Issue by SimranLahrani842** [GameSphere-MultiPlayer/GameSphere#777]
## Game Name
Single player game-Planet defense gane
## Description

You need to save planet earth.This is possible by hitting stones and meteroids hitting the planet.Use the gun to hit all of them.

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Aman1-coder** [comment]
@SimranLahrani842 Please add a demo vedio of gameplay

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 Please add a demo vedio of gameplay

I ll add a photo

**Comment by Durgesh4993** [comment]
@SimranLahrani842 This game is already existin repo...
