### ISSUE TITLE
README Need improvements 

### ISSUE THREAD

**Issue by RitiChandak** [GameSphere-MultiPlayer/GameSphere#780]
In the provided image, the number sequence is not properly structured as it contains repeated numbers and is written in a repetitive manner.

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/96969496/58e4be58-0ab8-43d5-9fd1-9b0b29a5bffe)

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98798977/855f9eb5-8133-47d6-9078-8d3372998c05)

**Comment by Durgesh4993** [comment]
@RitiChandak Could you also resolve that

**Comment by RitiChandak** [comment]
Ya sure happy to do it
