### ISSUE TITLE
Cloning number game 

### ISSUE THREAD

**Issue by Kalivarapubindusree** [GameSphere-MultiPlayer/GameSphere#781]
I want to add doubling of a number and crashing .
The other similar number and doubling the numbers 
Can you please assign me this task under GSSOC'23 contribution @Durgesh4993

**Comment by Durgesh4993** [comment]
@Kalivarapubindusree please add a screenshort or demo vedio

**Comment by Kalivarapubindusree** [comment]
![IMG_20230712_220125](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/114821855/e92ba5ef-4772-4fc9-8818-33a5bdb088ff)
This is the picture @Durgesh4993
