### ISSUE TITLE
Fix text in landing page

### ISSUE THREAD

**Issue by Sriparno08** [GameSphere-MultiPlayer/GameSphere#790]
We can change this text:

> In this platform we are here to play games with our friends at a same time without any interuption Our primary goal is to create a plateform where two or more friends can gather and play games online (such as multiplayer) without having to download any software or tools to their computers or mobile devices.

to:

> On this platform, we are here to play games with our friends at the same time without any interruption. Our primary goal is to create a platform where two or more friends can gather and play games online (such as multiplayer) without having to download any software or tools to their computers or mobile devices.

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/89148144/fd12947f-2cd1-47db-897f-be2b8450579d)

I would like to work on this as part of GSSOC'23.

**Comment by Manish12-verma** [comment]
I would like to work on this as part of GSSOC'23.
