### ISSUE TITLE
Shadow Poke guess game 

### ISSUE THREAD

**Issue by Kalivarapubindusree** [GameSphere-MultiPlayer/GameSphere#791]
I want to add shadow Pokemon guess game using HTML CSS javascript
Can you please assign me this task under GSSOC'23 contribution @Durgesh4993

**Comment by Aman1-coder** [comment]
@Kalivarapubindusree Please Follow the template

**Comment by Kalivarapubindusree** [comment]
Can you please tell me which template I had to follow??? @Aman1-coder
