### ISSUE TITLE
Angry     Bird Game

### ISSUE THREAD

**Issue by akankshachanana1** [GameSphere-MultiPlayer/GameSphere#793]
## Game Name
Angry Bird Game
## Description

Game logic and basic description
In Angry Birds, players control a group of colorful birds with different abilities who are seeking revenge on a group of green pigs that have stolen their eggs. The objective of the game is to launch the birds from a slingshot and strategically destroy various structures and obstacles in order to eliminate the pigs and retrieve the stolen eggs.

## Screenshot Section

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/127978268/e362574d-4f0e-4709-b898-aac1932fade4)

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/127978268/14010543-46a0-4194-8253-6323220f900e

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
@akankshachanana1 Can you make it responsive and full screen

**Comment by akankshachanana1** [comment]
yes,i will do that
