### ISSUE TITLE
Change the UI of the cards : Add 3D Sliding Effect

### ISSUE THREAD

**Issue by Shuchita33** [GameSphere-MultiPlayer/GameSphere#794]
This design of the cards is not so appealing.

![cards](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100029047/998adecc-3fa5-4a5f-b13c-0ee5b62e139e)

I wish to add this design into the project

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100029047/cc29a32e-d19c-40e0-a739-0161c635a944

Please allow me to add this effect and contribute to this project.

**Comment by Durgesh4993** [comment]
@Shuchita33 Thank you but we don't want to change it..
