### ISSUE TITLE
[BUG]: bug in the footer section of the game

### ISSUE THREAD

**Issue by Parul1606** [GameSphere-MultiPlayer/GameSphere#797]
I would like to fix the bug in the game section. 2 games have been added in the footer section which is out of the game section. 
I will be adding those in the game card section to fix the bug as it's not looking good on the website.

I am adding the screenshots of the bug: -

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/80768852/9c700384-29cf-4fbc-95e0-9741d1cdd9c6)

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/80768852/15f98864-855d-42bd-8489-26b126f0e66e)

**Comment by Durgesh4993** [comment]
Ok
