### ISSUE TITLE
Newsletter is not working

### ISSUE THREAD

**Issue by Nishitbaria** [GameSphere-MultiPlayer/GameSphere#828]
###  **Description:**
I am experiencing an issue with the newsletter feature on our GitHub repository. As the repository's administrator, I have set up the newsletter to keep our community informed about important updates, but it seems that the newsletter functionality is not working as expected.

### **Expected Behavior:**
The newsletter should be sent out to all subscribers on a regular basis (daily, weekly, or monthly, depending on the settings), providing them with updates about the repository, including new releases, pull requests, and important announcements.

### **Current Behavior:**
As of now, the newsletter is not being sent out at all. Despite setting the appropriate frequency and verifying that subscribers are correctly added, no newsletters are being delivered to the subscribers' email addresses.

### **Steps to Reproduce:**
1. Access the repository settings and navigate to the "Newsletter" section.
2. Configure the newsletter settings, including the frequency of sending and the list of subscribers.
3. Create new releases or important announcements that should trigger the newsletter.

### **Expected Outcome:**
The newsletter should be sent out automatically based on the specified frequency, and all subscribers should receive the relevant updates via email.

### **Actual Outcome:**
The newsletter is not being sent out, and subscribers are not receiving any updates via email.

**Comment by Nishitbaria** [comment]
hey @Durgesh4993  Please assign me this issue

**Comment by Durgesh4993** [comment]
@Nishitbaria when you send a demo vedio, or PR then i'll decide the lebels after see your work, if you are intresed you can start

**Comment by Nishitbaria** [comment]
@Durgesh4993 ,I will make pull request asap
