### ISSUE TITLE
Elephant Taco Game

### ISSUE THREAD

**Issue by uzmaansari23** [GameSphere-MultiPlayer/GameSphere#846]
## Game Name
Elephant Taco Game
## Description
This game is built with React, SVG, and GreenSock. It's about a hipster elephant who wants to get tacos but his friends keep trying to change plans .

Once there was an elephant. He was excited to go out with his friends and get tacos, but they kept texting him to change the plans. Help the elephant get all the tacos and avoid flakey text messages to get to delicious glory!

## Screenshot Section
![elephant](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/113499701/ad59c0d3-a072-4110-bca5-ce7cdce54ad5)

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by uzmaansari23** [comment]
Please assign me this issue under gssoc'23.

**Comment by uzmaansari23** [comment]
@Durgesh4993 why did you closed the issue as completed?

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98798977/3866fa69-93f3-4370-ac88-d58f22a548a9)

This is the reason

**Comment by uzmaansari23** [comment]
Is it not allowed to put the same game in different projects?

**Comment by uzmaansari23** [comment]
@Durgesh4993 Is it not allowed to put the same game in different projects?
