### ISSUE TITLE
[New game]: Bingo Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [GameSphere-MultiPlayer/GameSphere#87]
### 🎮 Game Request

Game logic and basic description
1. This is game is go for any number for players.
2. There are 25 numbers will keep in the game.
3. In one move, one player tell which number will he/she want to cut, that number will also be cut down by each and every member of the game.

### Point down the features

Game points

1. In this game, Winner will decide when the winner one will cut the all the letters of the "BINGO".

2. Letter of the BINGO can be cut when a straight line passing through those 5 numbers which are cut marked by the members.

3. One cut mark number can also be part of the other straight line.

4. This game will give user a best experience.

5. Result will be declared and stored for each and every rounds till the user is playing the game on the website.

So, Please assign this game task to me, please !

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
Please assign this new game to me, please !

**Comment by Aman1-coder** [comment]
I'll assign you @Avdhesh-Varshney 
If you need any help ask to mentor?
Connect with mentor:
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by Avdhesh-Varshney** [comment]
Thank you @Aman1-coder for assign this task to me

**Comment by Avdhesh-Varshney** [comment]
@Durgesh4993 Sir, I have done this game but in the repository it is shown that you had committed this game ?
So, please close this issue and marked bingo game committed by me.
Thanks for merge my pull request !
