### ISSUE TITLE
[Style]: Modfiy Navbar

### ISSUE THREAD

**Issue by parasss19** [GameSphere-MultiPlayer/GameSphere#886]
## Description
- Right now the navbar is not sticky
- As a user of your its very time consuming to every time go up to explore the website
- Also the Ui is not looking good 

## Changes
- I will made it sticky at top for easy access to users
- I also add glass morphism effect on it 

## Sample

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/101205226/100c7398-a255-4c2c-a1f7-3a7401a1a9b8

**Comment by parasss19** [comment]
Hey  @Durgesh4993 Please review it ASAP

**Comment by Durgesh4993** [comment]
@parasss19 No, we don't want to change navbar please raise any other issue
