### ISSUE TITLE
Math Game

### ISSUE THREAD

**Issue by Venkat-Vivek** [GameSphere-MultiPlayer/GameSphere#887]
## Description

Adding new game math game

Tech-stack used: Html, Css and Javascript.

Expected behavior
1.Math expression is generated over the display.
2.Timer gets started.
3.User needs solve the expression within the time.
4.Scoreboard is displayed.

## Screenshot Section

![mathgame](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/120968489/a34815b3-dd69-4e94-977d-d8c765d328ab)

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Venkat-Vivek** [comment]
@Durgesh4993 Assign this issue to me

**Comment by Durgesh4993** [comment]
@Venkat-Vivek Please raise any other issue because this type of game is already exist
