### ISSUE TITLE
[Game]:  want to add SIMON GAME

### ISSUE THREAD

**Issue by pallasivasai** [GameSphere-MultiPlayer/GameSphere#916]
## Game Name

SIMON GAME

## Description

this a random color selection game which is very fun and challenging game!

## Screenshot Section

![Simon - Google Chrome 09-05-2024 19_34_28](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/56314427/64e4d511-2457-46cb-b4eb-04838ed778cb)

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by pallasivasai** [comment]
please give GSSOC'24 label!

**Comment by anshmanitripathi** [comment]
Assign this task to me , I want to work upon this.
![Screenshot (70)](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/143960008/f27dd21e-3fff-4041-b51a-c7fb70773a3a)

**Comment by pallasivasai** [comment]
![MINGW64__c_Users_P siva sai_Desktop_git_sai_GameSphere_SinglePlayer - Games_SIMON_GAME 17-05-2024 8_12_25](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/56314427/67000254-5941-4827-8c6f-1013346ac420)


why am always getting this error please help!
