### ISSUE TITLE
The Theme colors section is not properly aligned to navbar

### ISSUE THREAD

**Issue by shnwz-solves** [GameSphere-MultiPlayer/GameSphere#924]
The theme color section is getting on over the navbar bottom line.
I would like to solve this issue, please assign this to me. Thankyou!
![Screenshot 2024-05-11 205142](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/126380641/7e56f919-813d-4412-b8f7-d78afefc4a01)

**Comment by Swapnil-Bhatnagar** [comment]
Please assign this to me . I want to work on this issue!

**Comment by somrima-09** [comment]
**Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.**

**Comment by shnwz-solves** [comment]
Thankyou PA @Durgesh4993 for assigning me this issue. I will try to solve it asap.

**Comment by shnwz-solves** [comment]
Hey PA @Durgesh4993 , please check the pull request: 
https://github.com/GameSphere-MultiPlayer/GameSphere/pull/944 
and review it. Thankyou.
