### ISSUE TITLE
Adding GSSoC image

### ISSUE THREAD

**Issue by Arpcoder** [GameSphere-MultiPlayer/GameSphere#932]
## Description
Adding GSSoC image would help contributors to know that this project is open for GSSoC contributions

## Severity
- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Critical

## Connect Us On social media -
- [ ]  Star the repositry
- [ ]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by somrima-09** [comment]
**Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.**
