### ISSUE TITLE
[Feature Request] :Adding logo to the title in navbar

### ISSUE THREAD

**Issue by harikasayani** [GameSphere-MultiPlayer/GameSphere#945]
## About Feature
I found logo is missing beside the title
## Description
I want to add the logo to look more attractive
## Technologies Used
HTML
CSS
## Connect Us On Social Media -
- [ ]  Star the repositry
- [ ]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
