### ISSUE TITLE
[Feature Request] :Contact form enhancement

### ISSUE THREAD

**Issue by harinisayani** [GameSphere-MultiPlayer/GameSphere#946]
## About Feature
I want to make contact form more attractive.
## Description
I want to add icons to the input fields to look attractive.
## Technologies Used
HTML,CSS
## Connect Us On Social Media -
- [ ]  Star the repositry
- [ ]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
