### ISSUE TITLE
[Game]: Hand Cricket Champ

### ISSUE THREAD

**Issue by CoderUzumaki** [GameSphere-MultiPlayer/GameSphere#948]
## Game Name
**Hand Cricket Champ**
## Description

My hand cricket game offers an engaging single-player experience where players face off against a bot opponent. The game begins with a toss feature, allowing the player who wins to choose between batting or bowling first. Its user-friendly interface includes captivating graphics designed to keep players immersed in the gameplay. Additionally, there is an instructions page within the game for newcomers to understand the rules and mechanics.

**The game's features include:**

- Toss feature for determining batting/bowling order.
- Captivating graphics enhancing user engagement.
- Instructions page for easy understanding of game rules. 

## Screenshot Section

![Screenshot 2024-05-15 170047](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/149368945/b874a9da-6d62-41b1-9536-012e54b28155)

![114](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/149368945/b31b8326-f9da-40d8-a3d4-eec38c2bdfec)

### Connect Us On Social Media -
- [X]  Star the repositry
- [X]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
