### ISSUE TITLE
[Game]: rock paper ans scissors

### ISSUE THREAD

**Issue by nagamukesh** [GameSphere-MultiPlayer/GameSphere#951]
## Description

Rock Paper and scissors is a classical two-player game but here, I want the second player to be a computer
so the user will be playing with computer 
This game is present in the repo but when I tried to search in the website, it didn't show up
please assign this issue to me under gssoc 2024
I can fix this

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
