### ISSUE TITLE
Typo error in the website

### ISSUE THREAD

**Issue by Ajita369** [GameSphere-MultiPlayer/GameSphere#954]
## Screenshots : 
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/162597493/3dc20aeb-da4f-42d5-98ba-424bc0dd2c0e)
in this paragraph spelling and punctuation error.
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/162597493/a638d75b-3d62-4022-a092-e1a724c38418)
in this the last line is not complete after "good".

I will like to work on this issue so please assign this issue to me under GSSOC'24.

## Connect Us On Social Media -
- [ ]  Star the repositry
- [ ]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
