### ISSUE TITLE
[Documentation]: Add contributors to the README.md 

### ISSUE THREAD

**Issue by tayyab-ilyas** [GameSphere-MultiPlayer/GameSphere#96]
### Describe the bug ✍️

I'd like to add the contributors profile images to the README.md, it will also keep updating itself as new contributors are added to project!

Here's an example:

![contr](https://github.com/Aman1-coder/GameSphere/assets/110786036/65d2e31b-576d-4072-812d-af20076379e1)

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by tayyab-ilyas** [comment]
hi @Aman1-coder ! can you assign this to me under GSSoc'23? thanks!

**Comment by Aman1-coder** [comment]
I'll assign you @tayyab-ilyas 
If you need any help ask to mentor?
Connect - 
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993
