### ISSUE TITLE
[Feature Request] : footer redirection is not working 

### ISSUE THREAD

**Issue by agastya3636** [GameSphere-MultiPlayer/GameSphere#960]
## About Feature
Footer redirection is not working I would like to fix it.
## Technologies Used
html
## Screenshot
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/124435030/337e0309-066d-41c8-84a4-59c1d2db80c3)

## Connect Us On Social Media -
- [ ]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by agastya3636** [comment]
@Durgesh4993 fixed it please  check it https://github.com/GameSphere-MultiPlayer/GameSphere/pull/961

**Comment by Varshajha5** [comment]
@Durgesh4993 please assign this issue to me  under gssoc 2024
