### ISSUE TITLE
[Game]: SnakeBites

### ISSUE THREAD

**Issue by SrijaVuppala295** [GameSphere-MultiPlayer/GameSphere#962]
## Game Name

SnakeBites 

## Description

Overview:
Snake Bites is a modern twist on the classic Snake game, offering an engaging and challenging experience for players of all ages. Control the hungry snake as it slithers around the screen, eating food to grow longer while avoiding collisions with the walls and its own tail. With multiple difficulty levels, Snake Bites provides endless fun and tests your reflexes and strategic thinking. 

Features:

Difficulty Levels:

Choose from three difficulty levels to match your skill and preference:
Easy (Speed: 5): A slower pace, perfect for beginners and those looking to relax.
Medium (Speed: 10): A moderate pace for experienced players seeking a challenge.
Hard (Speed: >15): A fast-paced, intense experience for experts who crave a real test of their reflexes.

Simple Controls:

Use the arrow keys or swipe gestures (on touch devices) to guide the snake in the desired direction.
Responsive controls ensure a smooth and enjoyable gameplay experience.

Scoring System:

Earn points by eating food items that appear randomly on the screen.
Your score increases with each item consumed, and the snake grows longer, making the game progressively more challenging.
Track your current score and high score to compete with yourself and others.

## Screenshot Section

###The User can select levels according to the difficulty

![Screenshot 2024-05-17 212940](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/140592148/b05f8461-38ee-4593-bf9e-27550772ac76)

 ### The game tracks the HighScore everytime the user plays!!

![Screenshot 2024-05-17 213021](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/140592148/f24b5e17-d110-4025-b4c6-140d0e14fa69)

## Demo Video Section

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/140592148/97c5cf76-0850-4366-af41-e39af6296ccc

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
