### ISSUE TITLE
General Knowledge Quiz

### ISSUE THREAD

**Issue by isha-dutta** [GameSphere-MultiPlayer/GameSphere#964]
## Description

Dive into an engaging quiz game crafted with HTML, CSS, and JavaScript. Challenge yourself with a series of questions, each with a strict 15-second time limit. Correct answers are crucial as there's no going back—question navigation is disabled to keep the game fast-paced and thrilling.

Key Features:

Time Challenge: Each question must be answered within 15 seconds, adding a layer of excitement and urgency.
No Navigation: Players must think quickly and answer on the spot—no going back to previous questions.
Interactive Design: Enjoy a visually appealing interface with smooth transitions and animations.
Score Tracking: Keep track of your performance and strive to improve with each attempt.

## Screenshot Section

![Screenshot 2024-05-18 010948](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/134736220/b45b759d-4930-4235-8587-80a70dadfff3)
<img width="914" alt="image" src="https://github.com/GameSphere-MultiPlayer/GameSphere/assets/134736220/5e3bbadf-fdd1-43fa-9f8c-207b92858f2a">
<img width="911" alt="image" src="https://github.com/GameSphere-MultiPlayer/GameSphere/assets/134736220/1a52bbf2-0d0e-47d3-8ea4-d11f0710fa9c">

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
