### ISSUE TITLE
Improper position of text and final score is not displayed - simon says

### ISSUE THREAD

**Issue by Dhruv-Gaba** [GameSphere-MultiPlayer/GameSphere#975]
## About Feature
The victory text in the simon game is overlapped and is not visible properly. also when we lose the final score is not shown.

## Description
the victory message can be properly aligned and the final score of the player can be shown even if he loses the game.

## Screenshot

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/141745373/8626a30d-19e7-41a1-93f1-44fe18e31da7)

## Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### Thank you for raising issue in GameSpher 3.0

please assign this issue to me under GSSOC'24.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
