### ISSUE TITLE
[Gssoc'23] Add social media icons below game category for users to contact conveniently horizontally in bigger size in webpage.

### ISSUE THREAD

**Issue by prathanab** [GameSphere-MultiPlayer/GameSphere#98]
while we scroll through a website we always checkout social media accounts so they be easy to find for user in bigger size.

![WhatsApp Image 2023-05-26 at 10 36 24 PM](https://github.com/Aman1-coder/GameSphere/assets/121685069/5e81ddfb-6aba-4496-a6d1-da68af9f109c)

**Comment by prathanab** [comment]
assign this to me @Aman1-coder

**Comment by Aman1-coder** [comment]
I'll assign you @prathanab 
If you need any help ask to mentor?
Connect with mentor:
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by Diya1418** [comment]
I would like to work on this issue. Please assign it to me.
