### ISSUE TITLE
[Feature Request] :Would u like to add Snake Animation to Readme.md file?

### ISSUE THREAD

**Issue by Anjaliavv51** [GameSphere-MultiPlayer/GameSphere#985]
### 🎮 feature Request

feature logic and basic description

https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/154777864/dee077c5-6d1e-40cb-9cd2-824f24c59982

### Point down the features

feature points
Shows the Graph of Contributions in this repo!

## Connect Us On Social Media -
- [X]  Star the repositry
- [X]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Amancoder-01** [comment]
Follow Us :
LinkedIn: https://www.linkedin.com/company/chromegaming
GitHub: https://github.com/GameSphere-MultiPlayer

Thank you :)
