### ISSUE TITLE
[Feature Request] : Adding Documentation for Angry Birds

### ISSUE THREAD

**Issue by manmita** [GameSphere-MultiPlayer/GameSphere#989]
## About Feature

Adding a README.md file in Angry Birds describing the game, and the working video in the assets folder.

## Description

The README.md file will include following points:

- Introduction 
- How to play

## Connect Us On Social Media -
- [X]  Star the repositry
- [X]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Amancoder-01** [comment]
Follow Us :
LinkedIn: https://www.linkedin.com/company/chromegaming
GitHub: https://github.com/GameSphere-MultiPlayer

Thank you :)
