### ISSUE TITLE
Auto Commenting when a PR is merged 

### ISSUE THREAD

**Issue by suhanipaliwal** [GameSphere-MultiPlayer/GameSphere#991]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by Amancoder-01** [comment]
Follow Us :
LinkedIn: https://www.linkedin.com/company/chromegaming
GitHub: https://github.com/GameSphere-MultiPlayer

Thank you :)
