### ISSUE TITLE
Improvement Suggestion for Website Contact Information

### ISSUE THREAD

**Issue by kashisharora9462** [GameSphere-MultiPlayer/GameSphere#995]
## About Feature
I noticed that your website is missing some crucial contact information such as phone numbers, email addresses, and a physical location. This omission can detract from the overall user experience, turning an otherwise excellent website into a less effective one.

If you prefer not to provide a phone number or physical location, you might consider including links to your LinkedIn, Instagram, and website instead. These platforms also offer effective ways for users to reach out to you.Please assign me this under GSsoc'24

## Technologies Used

I can do using css, javascript and animation
## Screenshot
![Screenshot 2024-05-23 174632](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/153215875/d524de37-24ce-46ed-9cce-5c0c7c5ddcab)

## Connect Us On Social Media -

- [x ]  Star the repositry
- [x ]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Amancoder-01** [comment]
Follow Us :
LinkedIn: https://www.linkedin.com/company/chromegaming
GitHub: https://github.com/GameSphere-MultiPlayer

Thank you :)

**Comment by kashisharora9462** [comment]
@Amancoder-01 please merge this with your repository to make that better.

**Comment by kashisharora9462** [comment]
Hello Sir,

I would like to request that you merge the contact-related changes I made
in the repository to close issue #995. These updates are essential for
improving the appearance and functionality of our website.

On my laptop, I have the most recent version of the code, and I have
committed all relevant changes to the updated repository. To ensure that
any new modifications are based on the latest and correct version, it is
crucial to merge the existing changes first. This will also allow me to
address another issue more effectively without introducing any conflicts or
errors.

Best Regards
Kashish Ahuja
